namespace AGAD.Migrations
{
    using System;
    using System.Collections.Generic;
    using System.Data.Entity;
    using System.Data.Entity.Migrations;
    using System.Linq;
    


    internal sealed class Configuration : DbMigrationsConfiguration<AGAD.Models.agadContext>
    {
        public Configuration()
        {
            AutomaticMigrationsEnabled = true;
        }
        private void seedAGADTYPE(AGAD.Models.agadContext context)
        {
            var dogalAfet = new List<AGAD.Models.AGADTYPE>
            {

                new AGAD.Models.AGADTYPE{
                    Id=1,
                    NAME="DEPREM",
                    NAMEUNICODE="deprem",
                    AGADs=null
                },
                 new AGAD.Models.AGADTYPE{
                    Id=2,
                    NAME="SEL",
                    NAMEUNICODE="sel",
                    AGADs=null
                }
            };

            dogalAfet.ForEach(f => context.AGADTYPEs.AddOrUpdate(p => p.Id, f));
            context.SaveChanges();
        }
        private void seedAGADCITY(AGAD.Models.agadContext context)
        {
            var list = new List<AGAD.Models.CITY>
            {
                new AGAD.Models.CITY{Id=1,NAME="Adana"},
                new AGAD.Models.CITY{Id=2,NAME="Adiyaman"},
                new AGAD.Models.CITY{Id=3,NAME="Afyon"},
                new AGAD.Models.CITY{Id=4,NAME="Aðri"},
                new AGAD.Models.CITY{Id=5,NAME="Amasya"},
                new AGAD.Models.CITY{Id=6,NAME="Ankara"},
                new AGAD.Models.CITY{Id=7,NAME="Antalya"},
                new AGAD.Models.CITY{Id=8,NAME="Artvin"},
                new AGAD.Models.CITY{Id=9,NAME="Aydin"},
                new AGAD.Models.CITY{Id=10,NAME="Balikesir"},
                new AGAD.Models.CITY{Id=11,NAME="Bilecik"},
                new AGAD.Models.CITY{Id=12,NAME="Bingöl"},
                new AGAD.Models.CITY{Id=13,NAME="Bitlis"},
                new AGAD.Models.CITY{Id=14,NAME="Bolu"},
                new AGAD.Models.CITY{Id=15,NAME="Burdur"},
                new AGAD.Models.CITY{Id=16,NAME="Bursa"},
                new AGAD.Models.CITY{Id=17,NAME="Çanakkale"},
                new AGAD.Models.CITY{Id=18,NAME="Çankiri"},
                new AGAD.Models.CITY{Id=19,NAME="Çorum"},
                new AGAD.Models.CITY{Id=20,NAME="DenizlÝ"},
                new AGAD.Models.CITY{Id=21,NAME="Diyarbakir"},
                new AGAD.Models.CITY{Id=22,NAME="Edirne"},
                new AGAD.Models.CITY{Id=23,NAME="Elazið"},
                new AGAD.Models.CITY{Id=24,NAME="Erzincan"},
                new AGAD.Models.CITY{Id=25,NAME="Erzurum"},
                new AGAD.Models.CITY{Id=26,NAME="Eskiþehir"},
                new AGAD.Models.CITY{Id=27,NAME="Gaziantep"},
                new AGAD.Models.CITY{Id=28,NAME="Giresun"},
                new AGAD.Models.CITY{Id=29,NAME="Gümüþhane"},
                new AGAD.Models.CITY{Id=30,NAME="Hakkari"},
                new AGAD.Models.CITY{Id=31,NAME="Hatay"},
                new AGAD.Models.CITY{Id=32,NAME="Isparta"},
                new AGAD.Models.CITY{Id=33,NAME="Ýçel"},
                new AGAD.Models.CITY{Id=34,NAME="Ýstanbul"},
                new AGAD.Models.CITY{Id=35,NAME="Ýzmir"},
                new AGAD.Models.CITY{Id=36,NAME="Kars"},
                new AGAD.Models.CITY{Id=37,NAME="Kastamonu"},
                new AGAD.Models.CITY{Id=38,NAME="KayserÝ"},
                new AGAD.Models.CITY{Id=39,NAME="Kirklareli"},
                new AGAD.Models.CITY{Id=40,NAME="Kirþehir"},
                new AGAD.Models.CITY{Id=41,NAME="Kocaeli"},
                new AGAD.Models.CITY{Id=42,NAME="Konya"},
                new AGAD.Models.CITY{Id=43,NAME="Kütahya"},
                new AGAD.Models.CITY{Id=44,NAME="Malatya"},
                new AGAD.Models.CITY{Id=45,NAME="Manisa"},
                new AGAD.Models.CITY{Id=46,NAME="Kahramanmaraþ"},
                new AGAD.Models.CITY{Id=47,NAME="Mardin"},
                new AGAD.Models.CITY{Id=48,NAME="Muðla"},
                new AGAD.Models.CITY{Id=49,NAME="Muþ"},
                new AGAD.Models.CITY{Id=50,NAME="Nevþehir"},
                new AGAD.Models.CITY{Id=51,NAME="Niðde"},
                new AGAD.Models.CITY{Id=52,NAME="Ordu"},
                new AGAD.Models.CITY{Id=53,NAME="Rize"},
                new AGAD.Models.CITY{Id=54,NAME="Sakarya"},
                new AGAD.Models.CITY{Id=55,NAME="Samsun"},
                new AGAD.Models.CITY{Id=56,NAME="Siirt"},
                new AGAD.Models.CITY{Id=57,NAME="Sinop"},
                new AGAD.Models.CITY{Id=58,NAME="Sivas"},
                new AGAD.Models.CITY{Id=59,NAME="Tekirdað"},
                new AGAD.Models.CITY{Id=60,NAME="Tokat"},
                new AGAD.Models.CITY{Id=61,NAME="Trabzon"},
                new AGAD.Models.CITY{Id=62,NAME="TuncelÝ"},
                new AGAD.Models.CITY{Id=63,NAME="Þanliurfa"},
                new AGAD.Models.CITY{Id=64,NAME="Uþak"},
                new AGAD.Models.CITY{Id=65,NAME="Van"},
                new AGAD.Models.CITY{Id=66,NAME="Yozgat"},
                new AGAD.Models.CITY{Id=67,NAME="Zonguldak"},
                new AGAD.Models.CITY{Id=68,NAME="Aksaray"},
                new AGAD.Models.CITY{Id=69,NAME="Bayburt"},
                new AGAD.Models.CITY{Id=70,NAME="Karaman"},
                new AGAD.Models.CITY{Id=71,NAME="Kirikkale"},
                new AGAD.Models.CITY{Id=72,NAME="Batman"},
                new AGAD.Models.CITY{Id=73,NAME="Þirnak"},
                new AGAD.Models.CITY{Id=74,NAME="Bartin"},
                new AGAD.Models.CITY{Id=75,NAME="Ardahan"},
                new AGAD.Models.CITY{Id=76,NAME="Iðdir"},
                new AGAD.Models.CITY{Id=77,NAME="Yalova"},
                new AGAD.Models.CITY{Id=78,NAME="Karabük"},
                new AGAD.Models.CITY{Id=79,NAME="Kilis"},
                new AGAD.Models.CITY{Id=80,NAME="Osmaniye"},
                new AGAD.Models.CITY{Id=81,NAME="Düzce"}
            };
            list.ForEach(f => context.CITies.AddOrUpdate(p => p.Id, f));
            context.SaveChanges();
        }
        private void seedAGADTOWN(AGAD.Models.agadContext context)
        {

            var temp = new List<Models.TOWN>
            {
                new AGAD.Models.TOWN{Id=1,CITY_ID=1,NAME="Merkez"},
                new AGAD.Models.TOWN{Id=2,CITY_ID=1,NAME="Aladag"},
                new AGAD.Models.TOWN{Id=3,CITY_ID=1,NAME="Ceyhan"},
                new AGAD.Models.TOWN{Id=4,CITY_ID=1,NAME="Feke"},
                new AGAD.Models.TOWN{Id=5,CITY_ID=1,NAME="Imamoglu"},
                new AGAD.Models.TOWN{Id=6,CITY_ID=1,NAME="Karaisali"},
                new AGAD.Models.TOWN{Id=7,CITY_ID=1,NAME="Karatas"},
                new AGAD.Models.TOWN{Id=8,CITY_ID=1,NAME="Kozan"},
                new AGAD.Models.TOWN{Id=9,CITY_ID=1,NAME="Pozanti"},
                new AGAD.Models.TOWN{Id=10,CITY_ID=1,NAME="Saimbeyli"},
                new AGAD.Models.TOWN{Id=11,CITY_ID=1,NAME="Seyhan"},
                new AGAD.Models.TOWN{Id=12,CITY_ID=1,NAME="Tufanbeyli"},
                new AGAD.Models.TOWN{Id=13,CITY_ID=1,NAME="Yumurtalik"},
                new AGAD.Models.TOWN{Id=14,CITY_ID=1,NAME="Yüregir"},
                new AGAD.Models.TOWN{Id=15,CITY_ID=2,NAME="Merkez"},
                new AGAD.Models.TOWN{Id=16,CITY_ID=2,NAME="Besni"},
                new AGAD.Models.TOWN{Id=17,CITY_ID=2,NAME="Çelikhan"},
                new AGAD.Models.TOWN{Id=18,CITY_ID=2,NAME="Gerger"},
                new AGAD.Models.TOWN{Id=19,CITY_ID=2,NAME="Gölbasi"},
                new AGAD.Models.TOWN{Id=20,CITY_ID=2,NAME="Kahta"},
                new AGAD.Models.TOWN{Id=21,CITY_ID=2,NAME="Samsat"},
                new AGAD.Models.TOWN{Id=22,CITY_ID=2,NAME="Sincik"},
                new AGAD.Models.TOWN{Id=23,CITY_ID=2,NAME="Tut"},
                new AGAD.Models.TOWN{Id=24,CITY_ID=3,NAME="Merkez"},
                new AGAD.Models.TOWN{Id=25,CITY_ID=3,NAME="Basmakçi"},
                new AGAD.Models.TOWN{Id=26,CITY_ID=3,NAME="Bayat"},
                new AGAD.Models.TOWN{Id=27,CITY_ID=3,NAME="Bolvadin"},
                new AGAD.Models.TOWN{Id=28,CITY_ID=3,NAME="Çobanlar"},
                new AGAD.Models.TOWN{Id=29,CITY_ID=3,NAME="Çay"},
                new AGAD.Models.TOWN{Id=30,CITY_ID=3,NAME="Dazkiri"},
                new AGAD.Models.TOWN{Id=31,CITY_ID=3,NAME="Dinar"},
                new AGAD.Models.TOWN{Id=32,CITY_ID=3,NAME="Emirdag"},
                new AGAD.Models.TOWN{Id=33,CITY_ID=3,NAME="Evciler"},
                new AGAD.Models.TOWN{Id=34,CITY_ID=3,NAME="Hocalar"},
                new AGAD.Models.TOWN{Id=35,CITY_ID=3,NAME="Ihsaniye"},
                new AGAD.Models.TOWN{Id=36,CITY_ID=3,NAME="Iscehisar"},
                new AGAD.Models.TOWN{Id=37,CITY_ID=3,NAME="Kizilören"},
                new AGAD.Models.TOWN{Id=38,CITY_ID=3,NAME="Sandikli"},
                new AGAD.Models.TOWN{Id=39,CITY_ID=3,NAME="Sincanli"},
                new AGAD.Models.TOWN{Id=40,CITY_ID=3,NAME="Sultandagi"},
                new AGAD.Models.TOWN{Id=41,CITY_ID=3,NAME="Suhut"},
                new AGAD.Models.TOWN{Id=42,CITY_ID=4,NAME="Merkez"},
                new AGAD.Models.TOWN{Id=43,CITY_ID=4,NAME="Diyadin"},
                new AGAD.Models.TOWN{Id=44,CITY_ID=4,NAME="Dogubeyazit"},
                new AGAD.Models.TOWN{Id=45,CITY_ID=4,NAME="Eleskirt"},
                new AGAD.Models.TOWN{Id=46,CITY_ID=4,NAME="Hamur"},
                new AGAD.Models.TOWN{Id=47,CITY_ID=4,NAME="Patnos"},
                new AGAD.Models.TOWN{Id=48,CITY_ID=4,NAME="Tasliçay"},
                new AGAD.Models.TOWN{Id=49,CITY_ID=4,NAME="Tutak"},
                new AGAD.Models.TOWN{Id=50,CITY_ID=5,NAME="Merkez"},
                new AGAD.Models.TOWN{Id=51,CITY_ID=5,NAME="Göynücek"},
                new AGAD.Models.TOWN{Id=52,CITY_ID=5,NAME="Gümüshacikö"},
                new AGAD.Models.TOWN{Id=53,CITY_ID=5,NAME="Hamamözü"},
                new AGAD.Models.TOWN{Id=54,CITY_ID=5,NAME="Merzifon"},
                new AGAD.Models.TOWN{Id=55,CITY_ID=5,NAME="Suluova"},
                new AGAD.Models.TOWN{Id=56,CITY_ID=5,NAME="Tasova"},
                new AGAD.Models.TOWN{Id=57,CITY_ID=6,NAME="Merkez"},
                new AGAD.Models.TOWN{Id=58,CITY_ID=6,NAME="Akyurt"},
                new AGAD.Models.TOWN{Id=59,CITY_ID=6,NAME="Altindag"},
                new AGAD.Models.TOWN{Id=60,CITY_ID=6,NAME="Ayas"},
                new AGAD.Models.TOWN{Id=61,CITY_ID=6,NAME="Bala"},
                new AGAD.Models.TOWN{Id=62,CITY_ID=6,NAME="Beypazari"},
                new AGAD.Models.TOWN{Id=63,CITY_ID=6,NAME="ÇamlIdere"},
                new AGAD.Models.TOWN{Id=64,CITY_ID=6,NAME="Çankaya"},
                new AGAD.Models.TOWN{Id=65,CITY_ID=6,NAME="Çubuk"},
                new AGAD.Models.TOWN{Id=66,CITY_ID=6,NAME="Elmadag"},
                new AGAD.Models.TOWN{Id=67,CITY_ID=6,NAME="Etimesgut"},
                new AGAD.Models.TOWN{Id=68,CITY_ID=6,NAME="Evren"},
                new AGAD.Models.TOWN{Id=69,CITY_ID=6,NAME="Gölbasi"},
                new AGAD.Models.TOWN{Id=70,CITY_ID=6,NAME="Güdül"},
                new AGAD.Models.TOWN{Id=71,CITY_ID=6,NAME="Haymana"},
                new AGAD.Models.TOWN{Id=72,CITY_ID=6,NAME="Kalecik"},
                new AGAD.Models.TOWN{Id=73,CITY_ID=6,NAME="Kazan"},
                new AGAD.Models.TOWN{Id=74,CITY_ID=6,NAME="Keçiören"},
                new AGAD.Models.TOWN{Id=75,CITY_ID=6,NAME="Kizilcahama"},
                new AGAD.Models.TOWN{Id=76,CITY_ID=6,NAME="Mamak"},
                new AGAD.Models.TOWN{Id=77,CITY_ID=6,NAME="Nallihan"},
                new AGAD.Models.TOWN{Id=78,CITY_ID=6,NAME="Polatli"},
                new AGAD.Models.TOWN{Id=79,CITY_ID=6,NAME="Sincan"},
                new AGAD.Models.TOWN{Id=80,CITY_ID=6,NAME="Sereflikoçh"},
                new AGAD.Models.TOWN{Id=81,CITY_ID=6,NAME="Yenimahalle"},
                new AGAD.Models.TOWN{Id=82,CITY_ID=7,NAME="Merkez"},
                new AGAD.Models.TOWN{Id=83,CITY_ID=7,NAME="Akseki"},
                new AGAD.Models.TOWN{Id=84,CITY_ID=7,NAME="Alanya"},
                new AGAD.Models.TOWN{Id=85,CITY_ID=7,NAME="Demre"},
                new AGAD.Models.TOWN{Id=86,CITY_ID=7,NAME="Elmali"},
                new AGAD.Models.TOWN{Id=87,CITY_ID=7,NAME="Finike"},
                new AGAD.Models.TOWN{Id=88,CITY_ID=7,NAME="Gazipasa"},
                new AGAD.Models.TOWN{Id=89,CITY_ID=7,NAME="Gündogmus"},
                new AGAD.Models.TOWN{Id=90,CITY_ID=7,NAME="Ibradi"},
                new AGAD.Models.TOWN{Id=91,CITY_ID=7,NAME="Kale"},
                new AGAD.Models.TOWN{Id=92,CITY_ID=7,NAME="Kas"},
                new AGAD.Models.TOWN{Id=93,CITY_ID=7,NAME="Kemer"},
                new AGAD.Models.TOWN{Id=94,CITY_ID=7,NAME="Korkuteli"},
                new AGAD.Models.TOWN{Id=95,CITY_ID=7,NAME="Kumluca"},
                new AGAD.Models.TOWN{Id=96,CITY_ID=7,NAME="Manavgat"},
                new AGAD.Models.TOWN{Id=97,CITY_ID=7,NAME="Serik"},
                new AGAD.Models.TOWN{Id=98,CITY_ID=8,NAME="Merkez"},
                new AGAD.Models.TOWN{Id=99,CITY_ID=8,NAME="Ardanuç"},
                new AGAD.Models.TOWN{Id=100,CITY_ID=8,NAME="Arhavi"},
                new AGAD.Models.TOWN{Id=101,CITY_ID=8,NAME="Borçka"},
                new AGAD.Models.TOWN{Id=102,CITY_ID=8,NAME="Hopa"},
                new AGAD.Models.TOWN{Id=103,CITY_ID=8,NAME="Murgul"},
                new AGAD.Models.TOWN{Id=104,CITY_ID=8,NAME="Savsat"},
                new AGAD.Models.TOWN{Id=105,CITY_ID=8,NAME="Yusufeli"},
                new AGAD.Models.TOWN{Id=106,CITY_ID=9,NAME="Merkez"},
                new AGAD.Models.TOWN{Id=107,CITY_ID=9,NAME="Bozdogan"},
                new AGAD.Models.TOWN{Id=108,CITY_ID=9,NAME="Buharkent"},
                new AGAD.Models.TOWN{Id=109,CITY_ID=9,NAME="Çine"},
                new AGAD.Models.TOWN{Id=110,CITY_ID=9,NAME="Germencik"},
                new AGAD.Models.TOWN{Id=111,CITY_ID=9,NAME="Incirliova"},
                new AGAD.Models.TOWN{Id=112,CITY_ID=9,NAME="Karacasu"},
                new AGAD.Models.TOWN{Id=113,CITY_ID=9,NAME="Karpuzlu"},
                new AGAD.Models.TOWN{Id=114,CITY_ID=9,NAME="Koçarli"},
                new AGAD.Models.TOWN{Id=115,CITY_ID=9,NAME="Kösk"},
                new AGAD.Models.TOWN{Id=116,CITY_ID=9,NAME="Kusadasi"},
                new AGAD.Models.TOWN{Id=117,CITY_ID=9,NAME="Kuyucak"},
                new AGAD.Models.TOWN{Id=118,CITY_ID=9,NAME="Nazilli"},
                new AGAD.Models.TOWN{Id=119,CITY_ID=9,NAME="Söke"},
                new AGAD.Models.TOWN{Id=120,CITY_ID=9,NAME="Sultanhisar"},
                new AGAD.Models.TOWN{Id=121,CITY_ID=9,NAME="Yenihisar"},
                new AGAD.Models.TOWN{Id=122,CITY_ID=9,NAME="Yenipazar"},
                new AGAD.Models.TOWN{Id=123,CITY_ID=10,NAME="Merkez"},
                new AGAD.Models.TOWN{Id=124,CITY_ID=10,NAME="Ayvalik"},
                new AGAD.Models.TOWN{Id=125,CITY_ID=10,NAME="Akçay"},
                new AGAD.Models.TOWN{Id=126,CITY_ID=10,NAME="Balya"},
                new AGAD.Models.TOWN{Id=127,CITY_ID=10,NAME="Bandirma"},
                new AGAD.Models.TOWN{Id=128,CITY_ID=10,NAME="Bigadiç"},
                new AGAD.Models.TOWN{Id=129,CITY_ID=10,NAME="Burhaniye"},
                new AGAD.Models.TOWN{Id=130,CITY_ID=10,NAME="Dursunbey"},
                new AGAD.Models.TOWN{Id=131,CITY_ID=10,NAME="Edremit"},
                new AGAD.Models.TOWN{Id=132,CITY_ID=10,NAME="Erdek"},
                new AGAD.Models.TOWN{Id=133,CITY_ID=10,NAME="Gönen"},
                new AGAD.Models.TOWN{Id=134,CITY_ID=10,NAME="Gömeç"},
                new AGAD.Models.TOWN{Id=135,CITY_ID=10,NAME="Havran"},
                new AGAD.Models.TOWN{Id=136,CITY_ID=10,NAME="Ivrindi"},
                new AGAD.Models.TOWN{Id=137,CITY_ID=10,NAME="Kepsut"},
                new AGAD.Models.TOWN{Id=138,CITY_ID=10,NAME="Manyas"},
                new AGAD.Models.TOWN{Id=139,CITY_ID=10,NAME="Marmara"},
                new AGAD.Models.TOWN{Id=140,CITY_ID=10,NAME="Savastepe"},
                new AGAD.Models.TOWN{Id=141,CITY_ID=10,NAME="Sindirgi"},
                new AGAD.Models.TOWN{Id=142,CITY_ID=10,NAME="Susurluk"},
                new AGAD.Models.TOWN{Id=143,CITY_ID=11,NAME="Merkez"},
                new AGAD.Models.TOWN{Id=144,CITY_ID=11,NAME="Bozöyük"},
                new AGAD.Models.TOWN{Id=145,CITY_ID=11,NAME="Gölpazari"},
                new AGAD.Models.TOWN{Id=146,CITY_ID=11,NAME="Inhisar"},
                new AGAD.Models.TOWN{Id=147,CITY_ID=11,NAME="Osmaneli"},
                new AGAD.Models.TOWN{Id=148,CITY_ID=11,NAME="Pazaryeri"},
                new AGAD.Models.TOWN{Id=149,CITY_ID=11,NAME="Sögüt"},
                new AGAD.Models.TOWN{Id=150,CITY_ID=11,NAME="Yenipazar"},
                new AGAD.Models.TOWN{Id=151,CITY_ID=12,NAME="Merkez"},
                new AGAD.Models.TOWN{Id=152,CITY_ID=12,NAME="Adakli"},
                new AGAD.Models.TOWN{Id=153,CITY_ID=12,NAME="Genç"},
                new AGAD.Models.TOWN{Id=154,CITY_ID=12,NAME="Karliova"},
                new AGAD.Models.TOWN{Id=155,CITY_ID=12,NAME="Kigi"},
                new AGAD.Models.TOWN{Id=156,CITY_ID=12,NAME="Solhan"},
                new AGAD.Models.TOWN{Id=157,CITY_ID=12,NAME="Yayladere"},
                new AGAD.Models.TOWN{Id=158,CITY_ID=12,NAME="Yedisu"},
                new AGAD.Models.TOWN{Id=159,CITY_ID=13,NAME="Merkez"},
                new AGAD.Models.TOWN{Id=160,CITY_ID=13,NAME="Adilcevaz"},
                new AGAD.Models.TOWN{Id=161,CITY_ID=13,NAME="Ahlat"},
                new AGAD.Models.TOWN{Id=162,CITY_ID=13,NAME="Güroymak"},
                new AGAD.Models.TOWN{Id=163,CITY_ID=13,NAME="Hizan"},
                new AGAD.Models.TOWN{Id=164,CITY_ID=13,NAME="Mutki"},
                new AGAD.Models.TOWN{Id=165,CITY_ID=13,NAME="Tatvan"},
                new AGAD.Models.TOWN{Id=166,CITY_ID=14,NAME="Merkez"},
                new AGAD.Models.TOWN{Id=167,CITY_ID=14,NAME="Dörtdivan"},
                new AGAD.Models.TOWN{Id=168,CITY_ID=14,NAME="Gerede"},
                new AGAD.Models.TOWN{Id=169,CITY_ID=14,NAME="Göynük"},
                new AGAD.Models.TOWN{Id=170,CITY_ID=14,NAME="Kibriscik"},
                new AGAD.Models.TOWN{Id=171,CITY_ID=14,NAME="Mengen"},
                new AGAD.Models.TOWN{Id=172,CITY_ID=14,NAME="Mudurnu"},
                new AGAD.Models.TOWN{Id=173,CITY_ID=14,NAME="Seben"},
                new AGAD.Models.TOWN{Id=174,CITY_ID=14,NAME="Yeniçaga"},
                new AGAD.Models.TOWN{Id=175,CITY_ID=15,NAME="Merkez"},
                new AGAD.Models.TOWN{Id=176,CITY_ID=15,NAME="Altinyayla"},
                new AGAD.Models.TOWN{Id=177,CITY_ID=15,NAME="Aglasun"},
                new AGAD.Models.TOWN{Id=178,CITY_ID=15,NAME="Bucak"},
                new AGAD.Models.TOWN{Id=179,CITY_ID=15,NAME="Çavdir"},
                new AGAD.Models.TOWN{Id=180,CITY_ID=15,NAME="Çeltikçi"},
                new AGAD.Models.TOWN{Id=181,CITY_ID=15,NAME="Gölhisar"},
                new AGAD.Models.TOWN{Id=182,CITY_ID=15,NAME="Karamanli"},
                new AGAD.Models.TOWN{Id=183,CITY_ID=15,NAME="Kemer"},
                new AGAD.Models.TOWN{Id=184,CITY_ID=15,NAME="Tefenni"},
                new AGAD.Models.TOWN{Id=185,CITY_ID=15,NAME="Yesilova"},
                new AGAD.Models.TOWN{Id=186,CITY_ID=16,NAME="Merkez"},
                new AGAD.Models.TOWN{Id=187,CITY_ID=16,NAME="Büyükorhan"},
                new AGAD.Models.TOWN{Id=188,CITY_ID=16,NAME="Gemlik"},
                new AGAD.Models.TOWN{Id=189,CITY_ID=16,NAME="Gürsu"},
                new AGAD.Models.TOWN{Id=190,CITY_ID=16,NAME="Harmancik"},
                new AGAD.Models.TOWN{Id=191,CITY_ID=16,NAME="Inegöl"},
                new AGAD.Models.TOWN{Id=192,CITY_ID=16,NAME="Iznik"},
                new AGAD.Models.TOWN{Id=193,CITY_ID=16,NAME="Karacabey"},
                new AGAD.Models.TOWN{Id=194,CITY_ID=16,NAME="Keles"},
                new AGAD.Models.TOWN{Id=195,CITY_ID=16,NAME="Kestel"},
                new AGAD.Models.TOWN{Id=196,CITY_ID=16,NAME="Mudanya"},
                new AGAD.Models.TOWN{Id=197,CITY_ID=16,NAME="Mustafakema"},
                new AGAD.Models.TOWN{Id=198,CITY_ID=16,NAME="Nilüfer"},
                new AGAD.Models.TOWN{Id=199,CITY_ID=16,NAME="Orhaneli"},
                new AGAD.Models.TOWN{Id=200,CITY_ID=16,NAME="Orhangazi"},
                new AGAD.Models.TOWN{Id=201,CITY_ID=16,NAME="Osmangazi"},
                new AGAD.Models.TOWN{Id=202,CITY_ID=16,NAME="Yenisehir"},
                new AGAD.Models.TOWN{Id=203,CITY_ID=16,NAME="Yildirim"},
                new AGAD.Models.TOWN{Id=204,CITY_ID=17,NAME="Merkez"},
                new AGAD.Models.TOWN{Id=205,CITY_ID=17,NAME="Ayvacik"},
                new AGAD.Models.TOWN{Id=206,CITY_ID=17,NAME="Bayramiç"},
                new AGAD.Models.TOWN{Id=207,CITY_ID=17,NAME="Bozcaada"},
                new AGAD.Models.TOWN{Id=208,CITY_ID=17,NAME="Biga"},
                new AGAD.Models.TOWN{Id=209,CITY_ID=17,NAME="Çan"},
                new AGAD.Models.TOWN{Id=210,CITY_ID=17,NAME="Eceabat"},
                new AGAD.Models.TOWN{Id=211,CITY_ID=17,NAME="Ezine"},
                new AGAD.Models.TOWN{Id=212,CITY_ID=17,NAME="Gelibolu"},
                new AGAD.Models.TOWN{Id=213,CITY_ID=17,NAME="Gökçeada"},
                new AGAD.Models.TOWN{Id=214,CITY_ID=17,NAME="Lapseki"},
                new AGAD.Models.TOWN{Id=215,CITY_ID=17,NAME="Yenice"},
                new AGAD.Models.TOWN{Id=216,CITY_ID=18,NAME="Merkez"},
                new AGAD.Models.TOWN{Id=217,CITY_ID=18,NAME="Atkaracalar"},
                new AGAD.Models.TOWN{Id=218,CITY_ID=18,NAME="Bayramören"},
                new AGAD.Models.TOWN{Id=219,CITY_ID=18,NAME="Çerkes"},
                new AGAD.Models.TOWN{Id=220,CITY_ID=18,NAME="Eldivan"},
                new AGAD.Models.TOWN{Id=221,CITY_ID=18,NAME="Ilgaz"},
                new AGAD.Models.TOWN{Id=222,CITY_ID=18,NAME="Kizilirmak"},
                new AGAD.Models.TOWN{Id=223,CITY_ID=18,NAME="Korgun"},
                new AGAD.Models.TOWN{Id=224,CITY_ID=18,NAME="Kursunlu"},
                new AGAD.Models.TOWN{Id=225,CITY_ID=18,NAME="Orta"},
                new AGAD.Models.TOWN{Id=226,CITY_ID=18,NAME="Ovacik"},
                new AGAD.Models.TOWN{Id=227,CITY_ID=18,NAME="Sabanözü"},
                new AGAD.Models.TOWN{Id=228,CITY_ID=18,NAME="Yaprakli"},
                new AGAD.Models.TOWN{Id=229,CITY_ID=19,NAME="Merkez"},
                new AGAD.Models.TOWN{Id=230,CITY_ID=19,NAME="Alaca"},
                new AGAD.Models.TOWN{Id=231,CITY_ID=19,NAME="Bayat"},
                new AGAD.Models.TOWN{Id=232,CITY_ID=19,NAME="Bogazkale"},
                new AGAD.Models.TOWN{Id=233,CITY_ID=19,NAME="Dodurga"},
                new AGAD.Models.TOWN{Id=234,CITY_ID=19,NAME="Iskilip"},
                new AGAD.Models.TOWN{Id=235,CITY_ID=19,NAME="Kargi"},
                new AGAD.Models.TOWN{Id=236,CITY_ID=19,NAME="Laçin"},
                new AGAD.Models.TOWN{Id=237,CITY_ID=19,NAME="Mecitözü"},
                new AGAD.Models.TOWN{Id=238,CITY_ID=19,NAME="Oguzlar"},
                new AGAD.Models.TOWN{Id=239,CITY_ID=19,NAME="Ortaköy"},
                new AGAD.Models.TOWN{Id=240,CITY_ID=19,NAME="Osmancik"},
                new AGAD.Models.TOWN{Id=241,CITY_ID=19,NAME="Sungurlu"},
                new AGAD.Models.TOWN{Id=242,CITY_ID=19,NAME="Ugurludag"},
                new AGAD.Models.TOWN{Id=243,CITY_ID=20,NAME="Merkez"},
                new AGAD.Models.TOWN{Id=244,CITY_ID=20,NAME="Acipayam"},
                new AGAD.Models.TOWN{Id=245,CITY_ID=20,NAME="Akköy"},
                new AGAD.Models.TOWN{Id=246,CITY_ID=20,NAME="Babadag"},
                new AGAD.Models.TOWN{Id=247,CITY_ID=20,NAME="Baklan"},
                new AGAD.Models.TOWN{Id=248,CITY_ID=20,NAME="Bekilli"},
                new AGAD.Models.TOWN{Id=249,CITY_ID=20,NAME="Beyagaç"},
                new AGAD.Models.TOWN{Id=250,CITY_ID=20,NAME="Buldan"},
                new AGAD.Models.TOWN{Id=251,CITY_ID=20,NAME="Bozkurt"},
                new AGAD.Models.TOWN{Id=252,CITY_ID=20,NAME="Çal"},
                new AGAD.Models.TOWN{Id=253,CITY_ID=20,NAME="Çameli"},
                new AGAD.Models.TOWN{Id=254,CITY_ID=20,NAME="Çardak"},
                new AGAD.Models.TOWN{Id=255,CITY_ID=20,NAME="Çivril"},
                new AGAD.Models.TOWN{Id=256,CITY_ID=20,NAME="Güney"},
                new AGAD.Models.TOWN{Id=257,CITY_ID=20,NAME="Honaz"},
                new AGAD.Models.TOWN{Id=258,CITY_ID=20,NAME="Kale"},
                new AGAD.Models.TOWN{Id=259,CITY_ID=20,NAME="Sarayköy"},
                new AGAD.Models.TOWN{Id=260,CITY_ID=20,NAME="Serinhisar"},
                new AGAD.Models.TOWN{Id=261,CITY_ID=20,NAME="Tavas"},
                new AGAD.Models.TOWN{Id=262,CITY_ID=21,NAME="Merkez"},
                new AGAD.Models.TOWN{Id=263,CITY_ID=21,NAME="Bismil"},
                new AGAD.Models.TOWN{Id=264,CITY_ID=21,NAME="Çermik"},
                new AGAD.Models.TOWN{Id=265,CITY_ID=21,NAME="Çinar"},
                new AGAD.Models.TOWN{Id=266,CITY_ID=21,NAME="Çüngüs"},
                new AGAD.Models.TOWN{Id=267,CITY_ID=21,NAME="Dicle"},
                new AGAD.Models.TOWN{Id=268,CITY_ID=21,NAME="Egil"},
                new AGAD.Models.TOWN{Id=269,CITY_ID=21,NAME="Ergani"},
                new AGAD.Models.TOWN{Id=270,CITY_ID=21,NAME="Hani"},
                new AGAD.Models.TOWN{Id=271,CITY_ID=21,NAME="Hazro"},
                new AGAD.Models.TOWN{Id=272,CITY_ID=21,NAME="Kocaköy"},
                new AGAD.Models.TOWN{Id=273,CITY_ID=21,NAME="Kulp"},
                new AGAD.Models.TOWN{Id=274,CITY_ID=21,NAME="Lice"},
                new AGAD.Models.TOWN{Id=275,CITY_ID=21,NAME="Silvan"},
                new AGAD.Models.TOWN{Id=276,CITY_ID=22,NAME="Merkez"},
                new AGAD.Models.TOWN{Id=277,CITY_ID=22,NAME="Enez"},
                new AGAD.Models.TOWN{Id=278,CITY_ID=22,NAME="Havsa"},
                new AGAD.Models.TOWN{Id=279,CITY_ID=22,NAME="Ipsala"},
                new AGAD.Models.TOWN{Id=280,CITY_ID=22,NAME="Kesan"},
                new AGAD.Models.TOWN{Id=281,CITY_ID=22,NAME="Lalapasa"},
                new AGAD.Models.TOWN{Id=282,CITY_ID=22,NAME="Meriç"},
                new AGAD.Models.TOWN{Id=283,CITY_ID=22,NAME="Süloglu"},
                new AGAD.Models.TOWN{Id=284,CITY_ID=22,NAME="Uzunköprü"},
                new AGAD.Models.TOWN{Id=285,CITY_ID=23,NAME="Merkez"},
                new AGAD.Models.TOWN{Id=286,CITY_ID=23,NAME="Agin"},
                new AGAD.Models.TOWN{Id=287,CITY_ID=23,NAME="Alacakaya"},
                new AGAD.Models.TOWN{Id=288,CITY_ID=23,NAME="Aricak"},
                new AGAD.Models.TOWN{Id=289,CITY_ID=23,NAME="Baskil"},
                new AGAD.Models.TOWN{Id=290,CITY_ID=23,NAME="Karakoçan"},
                new AGAD.Models.TOWN{Id=291,CITY_ID=23,NAME="Keban"},
                new AGAD.Models.TOWN{Id=292,CITY_ID=23,NAME="Kovancilar"},
                new AGAD.Models.TOWN{Id=293,CITY_ID=23,NAME="Maden"},
                new AGAD.Models.TOWN{Id=294,CITY_ID=23,NAME="Palu"},
                new AGAD.Models.TOWN{Id=295,CITY_ID=23,NAME="Sivrice"},
                new AGAD.Models.TOWN{Id=296,CITY_ID=24,NAME="Merkez"},
                new AGAD.Models.TOWN{Id=297,CITY_ID=24,NAME="Çayirli"},
                new AGAD.Models.TOWN{Id=298,CITY_ID=24,NAME="Iliç"},
                new AGAD.Models.TOWN{Id=299,CITY_ID=24,NAME="Kemah"},
                new AGAD.Models.TOWN{Id=300,CITY_ID=24,NAME="Kemaliye"},
                new AGAD.Models.TOWN{Id=301,CITY_ID=24,NAME="Otlukbeli"},
                new AGAD.Models.TOWN{Id=302,CITY_ID=24,NAME="Refahiye"},
                new AGAD.Models.TOWN{Id=303,CITY_ID=24,NAME="Tercan"},
                new AGAD.Models.TOWN{Id=304,CITY_ID=24,NAME="Üzümlü"},
                new AGAD.Models.TOWN{Id=305,CITY_ID=25,NAME="Merkez"},
                new AGAD.Models.TOWN{Id=306,CITY_ID=25,NAME="Askale"},
                new AGAD.Models.TOWN{Id=307,CITY_ID=25,NAME="Çat"},
                new AGAD.Models.TOWN{Id=308,CITY_ID=25,NAME="Hinis"},
                new AGAD.Models.TOWN{Id=309,CITY_ID=25,NAME="Horasan"},
                new AGAD.Models.TOWN{Id=310,CITY_ID=25,NAME="Ilica"},
                new AGAD.Models.TOWN{Id=311,CITY_ID=25,NAME="Ispir"},
                new AGAD.Models.TOWN{Id=312,CITY_ID=25,NAME="Karaçoban"},
                new AGAD.Models.TOWN{Id=313,CITY_ID=25,NAME="Karayazi"},
                new AGAD.Models.TOWN{Id=314,CITY_ID=25,NAME="Köprüköy"},
                new AGAD.Models.TOWN{Id=315,CITY_ID=25,NAME="Narman"},
                new AGAD.Models.TOWN{Id=316,CITY_ID=25,NAME="Oltu"},
                new AGAD.Models.TOWN{Id=317,CITY_ID=25,NAME="Olur"},
                new AGAD.Models.TOWN{Id=318,CITY_ID=25,NAME="Pasinler"},
                new AGAD.Models.TOWN{Id=319,CITY_ID=25,NAME="Pazaryolu"},
                new AGAD.Models.TOWN{Id=320,CITY_ID=25,NAME="Senkaya"},
                new AGAD.Models.TOWN{Id=321,CITY_ID=25,NAME="Tekman"},
                new AGAD.Models.TOWN{Id=322,CITY_ID=25,NAME="Tortum"},
                new AGAD.Models.TOWN{Id=323,CITY_ID=25,NAME="Uzundere"},
                new AGAD.Models.TOWN{Id=324,CITY_ID=26,NAME="Merkez"},
                new AGAD.Models.TOWN{Id=325,CITY_ID=26,NAME="Alpu"},
                new AGAD.Models.TOWN{Id=326,CITY_ID=26,NAME="Beylikova"},
                new AGAD.Models.TOWN{Id=327,CITY_ID=26,NAME="Çifteler"},
                new AGAD.Models.TOWN{Id=328,CITY_ID=26,NAME="Günyüzü"},
                new AGAD.Models.TOWN{Id=329,CITY_ID=26,NAME="Han"},
                new AGAD.Models.TOWN{Id=330,CITY_ID=26,NAME="Inönü"},
                new AGAD.Models.TOWN{Id=331,CITY_ID=26,NAME="Mahmudiye"},
                new AGAD.Models.TOWN{Id=332,CITY_ID=26,NAME="Mihalgazi"},
                new AGAD.Models.TOWN{Id=333,CITY_ID=26,NAME="Mihaliççik"},
                new AGAD.Models.TOWN{Id=334,CITY_ID=26,NAME="Saricakaya"},
                new AGAD.Models.TOWN{Id=335,CITY_ID=26,NAME="Seyitgazi"},
                new AGAD.Models.TOWN{Id=336,CITY_ID=26,NAME="Sivrihisar"},
                new AGAD.Models.TOWN{Id=337,CITY_ID=27,NAME="Merkez"},
                new AGAD.Models.TOWN{Id=338,CITY_ID=27,NAME="Araban"},
                new AGAD.Models.TOWN{Id=339,CITY_ID=27,NAME="Islahiye"},
                new AGAD.Models.TOWN{Id=340,CITY_ID=27,NAME="Kilis"},
                new AGAD.Models.TOWN{Id=341,CITY_ID=27,NAME="Kargamis"},
                new AGAD.Models.TOWN{Id=342,CITY_ID=27,NAME="Nizip"},
                new AGAD.Models.TOWN{Id=343,CITY_ID=27,NAME="Nurdagi"},
                new AGAD.Models.TOWN{Id=344,CITY_ID=27,NAME="Oguzeli"},
                new AGAD.Models.TOWN{Id=345,CITY_ID=27,NAME="Sahinbey"},
                new AGAD.Models.TOWN{Id=346,CITY_ID=27,NAME="Sehitkamil"},
                new AGAD.Models.TOWN{Id=347,CITY_ID=27,NAME="Yavuzeli"},
                new AGAD.Models.TOWN{Id=348,CITY_ID=28,NAME="Merkez"},
                new AGAD.Models.TOWN{Id=349,CITY_ID=28,NAME="Alucra"},
                new AGAD.Models.TOWN{Id=350,CITY_ID=28,NAME="Bulancak"},
                new AGAD.Models.TOWN{Id=351,CITY_ID=28,NAME="Çamoluk"},
                new AGAD.Models.TOWN{Id=352,CITY_ID=28,NAME="Çanakçi"},
                new AGAD.Models.TOWN{Id=353,CITY_ID=28,NAME="Dereli"},
                new AGAD.Models.TOWN{Id=354,CITY_ID=28,NAME="Dogankent"},
                new AGAD.Models.TOWN{Id=355,CITY_ID=28,NAME="Espiye"},
                new AGAD.Models.TOWN{Id=356,CITY_ID=28,NAME="Eynesil"},
                new AGAD.Models.TOWN{Id=357,CITY_ID=28,NAME="Görele"},
                new AGAD.Models.TOWN{Id=358,CITY_ID=28,NAME="Güce"},
                new AGAD.Models.TOWN{Id=359,CITY_ID=28,NAME="Kesap"},
                new AGAD.Models.TOWN{Id=360,CITY_ID=28,NAME="Piraziz"},
                new AGAD.Models.TOWN{Id=361,CITY_ID=28,NAME="Sebinkarahisar"},
                new AGAD.Models.TOWN{Id=362,CITY_ID=28,NAME="Tirebolu"},
                new AGAD.Models.TOWN{Id=363,CITY_ID=28,NAME="YaglIdere"},
                new AGAD.Models.TOWN{Id=364,CITY_ID=29,NAME="Merkez"},
                new AGAD.Models.TOWN{Id=365,CITY_ID=29,NAME="Kelkit"},
                new AGAD.Models.TOWN{Id=366,CITY_ID=29,NAME="Köse"},
                new AGAD.Models.TOWN{Id=367,CITY_ID=29,NAME="Kürtün"},
                new AGAD.Models.TOWN{Id=368,CITY_ID=29,NAME="Siran"},
                new AGAD.Models.TOWN{Id=369,CITY_ID=29,NAME="Torul"},
                new AGAD.Models.TOWN{Id=370,CITY_ID=30,NAME="Merkez"},
                new AGAD.Models.TOWN{Id=371,CITY_ID=30,NAME="Çukurca"},
                new AGAD.Models.TOWN{Id=372,CITY_ID=30,NAME="Semdinli"},
                new AGAD.Models.TOWN{Id=373,CITY_ID=30,NAME="Yüksekova"},
                new AGAD.Models.TOWN{Id=374,CITY_ID=31,NAME="Merkez"},
                new AGAD.Models.TOWN{Id=375,CITY_ID=31,NAME="Altinözü"},
                new AGAD.Models.TOWN{Id=376,CITY_ID=31,NAME="Belen"},
                new AGAD.Models.TOWN{Id=377,CITY_ID=31,NAME="Dörtyol"},
                new AGAD.Models.TOWN{Id=378,CITY_ID=31,NAME="Erzin"},
                new AGAD.Models.TOWN{Id=379,CITY_ID=31,NAME="Hassa"},
                new AGAD.Models.TOWN{Id=380,CITY_ID=31,NAME="Iskenderun"},
                new AGAD.Models.TOWN{Id=381,CITY_ID=31,NAME="Kirikhan"},
                new AGAD.Models.TOWN{Id=382,CITY_ID=31,NAME="Kumlu"},
                new AGAD.Models.TOWN{Id=383,CITY_ID=31,NAME="Reyhanli"},
                new AGAD.Models.TOWN{Id=384,CITY_ID=31,NAME="Samandagi"},
                new AGAD.Models.TOWN{Id=385,CITY_ID=31,NAME="Yayladagi"},
                new AGAD.Models.TOWN{Id=386,CITY_ID=32,NAME="Merkez"},
                new AGAD.Models.TOWN{Id=387,CITY_ID=32,NAME="Aksu"},
                new AGAD.Models.TOWN{Id=388,CITY_ID=32,NAME="Atabey"},
                new AGAD.Models.TOWN{Id=389,CITY_ID=32,NAME="Egirdir"},
                new AGAD.Models.TOWN{Id=390,CITY_ID=32,NAME="Gelendost"},
                new AGAD.Models.TOWN{Id=391,CITY_ID=32,NAME="Gönen"},
                new AGAD.Models.TOWN{Id=392,CITY_ID=32,NAME="Keçiborlu"},
                new AGAD.Models.TOWN{Id=393,CITY_ID=32,NAME="Senirkent"},
                new AGAD.Models.TOWN{Id=394,CITY_ID=32,NAME="Sütçüler"},
                new AGAD.Models.TOWN{Id=395,CITY_ID=32,NAME="Sarkikaraag"},
                new AGAD.Models.TOWN{Id=396,CITY_ID=32,NAME="Uluborlu"},
                new AGAD.Models.TOWN{Id=397,CITY_ID=32,NAME="Yenisarbade"},
                new AGAD.Models.TOWN{Id=398,CITY_ID=32,NAME="Yalvaç"},
                new AGAD.Models.TOWN{Id=399,CITY_ID=33,NAME="Merkez"},
                new AGAD.Models.TOWN{Id=400,CITY_ID=33,NAME="Anamur"},
                new AGAD.Models.TOWN{Id=401,CITY_ID=33,NAME="Aydincik"},
                new AGAD.Models.TOWN{Id=402,CITY_ID=33,NAME="Bozyazi"},
                new AGAD.Models.TOWN{Id=403,CITY_ID=33,NAME="Çamliyayla"},
                new AGAD.Models.TOWN{Id=404,CITY_ID=33,NAME="Erdemli"},
                new AGAD.Models.TOWN{Id=405,CITY_ID=33,NAME="Gülnar"},
                new AGAD.Models.TOWN{Id=406,CITY_ID=33,NAME="Mut"},
                new AGAD.Models.TOWN{Id=407,CITY_ID=33,NAME="Silifke"},
                new AGAD.Models.TOWN{Id=408,CITY_ID=33,NAME="Tarsus"},
                new AGAD.Models.TOWN{Id=409,CITY_ID=34,NAME="Merkez"},
                new AGAD.Models.TOWN{Id=410,CITY_ID=34,NAME="Adalar"},
                new AGAD.Models.TOWN{Id=411,CITY_ID=34,NAME="Avcilar"},
                new AGAD.Models.TOWN{Id=412,CITY_ID=34,NAME="Bagcilar"},
                new AGAD.Models.TOWN{Id=413,CITY_ID=34,NAME="Bakirköy"},
                new AGAD.Models.TOWN{Id=414,CITY_ID=34,NAME="Bahçelievle"},
                new AGAD.Models.TOWN{Id=415,CITY_ID=34,NAME="Bayrampasa"},
                new AGAD.Models.TOWN{Id=416,CITY_ID=34,NAME="Besiktas"},
                new AGAD.Models.TOWN{Id=417,CITY_ID=34,NAME="Beykoz"},
                new AGAD.Models.TOWN{Id=418,CITY_ID=34,NAME="Beyoglu"},
                new AGAD.Models.TOWN{Id=419,CITY_ID=34,NAME="Büyükçekmece"},
                new AGAD.Models.TOWN{Id=420,CITY_ID=34,NAME="Çatalca"},
                new AGAD.Models.TOWN{Id=421,CITY_ID=34,NAME="Eminönü"},
                new AGAD.Models.TOWN{Id=422,CITY_ID=34,NAME="Eyüp"},
                new AGAD.Models.TOWN{Id=423,CITY_ID=34,NAME="Esenler"},
                new AGAD.Models.TOWN{Id=424,CITY_ID=34,NAME="Fatih"},
                new AGAD.Models.TOWN{Id=425,CITY_ID=34,NAME="Gaziosmanpasa"},
                new AGAD.Models.TOWN{Id=426,CITY_ID=34,NAME="Güngören"},
                new AGAD.Models.TOWN{Id=427,CITY_ID=34,NAME="Kadiköy"},
                new AGAD.Models.TOWN{Id=428,CITY_ID=34,NAME="Kagithane"},
                new AGAD.Models.TOWN{Id=429,CITY_ID=34,NAME="Kartal"},
                new AGAD.Models.TOWN{Id=430,CITY_ID=34,NAME="Küçükçekmece"},
                new AGAD.Models.TOWN{Id=431,CITY_ID=34,NAME="Maltepe"},
                new AGAD.Models.TOWN{Id=432,CITY_ID=34,NAME="Pendik"},
                new AGAD.Models.TOWN{Id=433,CITY_ID=34,NAME="Sariyer"},
                new AGAD.Models.TOWN{Id=434,CITY_ID=34,NAME="Silivri"},
                new AGAD.Models.TOWN{Id=435,CITY_ID=34,NAME="Sultanbeyli"},
                new AGAD.Models.TOWN{Id=436,CITY_ID=34,NAME="Sile"},
                new AGAD.Models.TOWN{Id=437,CITY_ID=34,NAME="Sisli"},
                new AGAD.Models.TOWN{Id=438,CITY_ID=34,NAME="Tuzla"},
                new AGAD.Models.TOWN{Id=439,CITY_ID=34,NAME="Ümraniye"},
                new AGAD.Models.TOWN{Id=440,CITY_ID=34,NAME="Üsküdar"},
                new AGAD.Models.TOWN{Id=441,CITY_ID=34,NAME="Yalova"},
                new AGAD.Models.TOWN{Id=442,CITY_ID=34,NAME="Zeytinburnu"},
                new AGAD.Models.TOWN{Id=443,CITY_ID=35,NAME="Merkez"},
                new AGAD.Models.TOWN{Id=444,CITY_ID=35,NAME="Aliaga"},
                new AGAD.Models.TOWN{Id=445,CITY_ID=35,NAME="Bayindir"},
                new AGAD.Models.TOWN{Id=446,CITY_ID=35,NAME="Balçova"},
                new AGAD.Models.TOWN{Id=447,CITY_ID=35,NAME="Bergama"},
                new AGAD.Models.TOWN{Id=448,CITY_ID=35,NAME="Beydag"},
                new AGAD.Models.TOWN{Id=449,CITY_ID=35,NAME="Bornova"},
                new AGAD.Models.TOWN{Id=450,CITY_ID=35,NAME="Buca"},
                new AGAD.Models.TOWN{Id=451,CITY_ID=35,NAME="Çesme"},
                new AGAD.Models.TOWN{Id=452,CITY_ID=35,NAME="Çigli"},
                new AGAD.Models.TOWN{Id=453,CITY_ID=35,NAME="Dikili"},
                new AGAD.Models.TOWN{Id=454,CITY_ID=35,NAME="Foça"},
                new AGAD.Models.TOWN{Id=455,CITY_ID=35,NAME="Gaziemir"},
                new AGAD.Models.TOWN{Id=456,CITY_ID=35,NAME="Güzelbahçe"},
                new AGAD.Models.TOWN{Id=457,CITY_ID=35,NAME="Karaburun"},
                new AGAD.Models.TOWN{Id=458,CITY_ID=35,NAME="Karsiyaka"},
                new AGAD.Models.TOWN{Id=459,CITY_ID=35,NAME="Kemalpasa"},
                new AGAD.Models.TOWN{Id=460,CITY_ID=35,NAME="Kinik"},
                new AGAD.Models.TOWN{Id=461,CITY_ID=35,NAME="Kiraz"},
                new AGAD.Models.TOWN{Id=462,CITY_ID=35,NAME="Konak"},
                new AGAD.Models.TOWN{Id=463,CITY_ID=35,NAME="Menderes"},
                new AGAD.Models.TOWN{Id=464,CITY_ID=35,NAME="Menemen"},
                new AGAD.Models.TOWN{Id=465,CITY_ID=35,NAME="NarlIdere"},
                new AGAD.Models.TOWN{Id=466,CITY_ID=35,NAME="Ödemis"},
                new AGAD.Models.TOWN{Id=467,CITY_ID=35,NAME="Seferihisar"},
                new AGAD.Models.TOWN{Id=468,CITY_ID=35,NAME="Selçuk"},
                new AGAD.Models.TOWN{Id=469,CITY_ID=35,NAME="Tire"},
                new AGAD.Models.TOWN{Id=470,CITY_ID=35,NAME="Torbali"},
                new AGAD.Models.TOWN{Id=471,CITY_ID=35,NAME="Urla"},
                new AGAD.Models.TOWN{Id=472,CITY_ID=36,NAME="Merkez"},
                new AGAD.Models.TOWN{Id=473,CITY_ID=36,NAME="Akyaka"},
                new AGAD.Models.TOWN{Id=474,CITY_ID=36,NAME="Arpaçay"},
                new AGAD.Models.TOWN{Id=475,CITY_ID=36,NAME="Digor"},
                new AGAD.Models.TOWN{Id=476,CITY_ID=36,NAME="Kagizman"},
                new AGAD.Models.TOWN{Id=477,CITY_ID=36,NAME="Sarikamis"},
                new AGAD.Models.TOWN{Id=478,CITY_ID=36,NAME="Selim"},
                new AGAD.Models.TOWN{Id=479,CITY_ID=36,NAME="Susuz"},
                new AGAD.Models.TOWN{Id=480,CITY_ID=37,NAME="Merkez"},
                new AGAD.Models.TOWN{Id=481,CITY_ID=37,NAME="Abana"},
                new AGAD.Models.TOWN{Id=482,CITY_ID=37,NAME="Agli"},
                new AGAD.Models.TOWN{Id=483,CITY_ID=37,NAME="Araç"},
                new AGAD.Models.TOWN{Id=484,CITY_ID=37,NAME="Azdavay"},
                new AGAD.Models.TOWN{Id=485,CITY_ID=37,NAME="Bozkurt"},
                new AGAD.Models.TOWN{Id=486,CITY_ID=37,NAME="CIde"},
                new AGAD.Models.TOWN{Id=487,CITY_ID=37,NAME="Çatalzeytin"},
                new AGAD.Models.TOWN{Id=488,CITY_ID=37,NAME="Daday"},
                new AGAD.Models.TOWN{Id=489,CITY_ID=37,NAME="Devrekani"},
                new AGAD.Models.TOWN{Id=490,CITY_ID=37,NAME="Doganyurt"},
                new AGAD.Models.TOWN{Id=491,CITY_ID=37,NAME="Hanönü"},
                new AGAD.Models.TOWN{Id=492,CITY_ID=37,NAME="Ihsangazi"},
                new AGAD.Models.TOWN{Id=493,CITY_ID=37,NAME="Inebolu"},
                new AGAD.Models.TOWN{Id=494,CITY_ID=37,NAME="Küre"},
                new AGAD.Models.TOWN{Id=495,CITY_ID=37,NAME="Pinarbasi"},
                new AGAD.Models.TOWN{Id=496,CITY_ID=37,NAME="Seydiler"},
                new AGAD.Models.TOWN{Id=497,CITY_ID=37,NAME="Senpazar"},
                new AGAD.Models.TOWN{Id=498,CITY_ID=37,NAME="Tasköprü"},
                new AGAD.Models.TOWN{Id=499,CITY_ID=37,NAME="Tosya"},
                new AGAD.Models.TOWN{Id=500,CITY_ID=38,NAME="Merkez"},
                new AGAD.Models.TOWN{Id=501,CITY_ID=38,NAME="Akkisla"},
                new AGAD.Models.TOWN{Id=502,CITY_ID=38,NAME="Bünyan"},
                new AGAD.Models.TOWN{Id=503,CITY_ID=38,NAME="Develi"},
                new AGAD.Models.TOWN{Id=504,CITY_ID=38,NAME="Felahiye"},
                new AGAD.Models.TOWN{Id=505,CITY_ID=38,NAME="Hacilar"},
                new AGAD.Models.TOWN{Id=506,CITY_ID=38,NAME="Incesu"},
                new AGAD.Models.TOWN{Id=507,CITY_ID=38,NAME="Kocasinan"},
                new AGAD.Models.TOWN{Id=508,CITY_ID=38,NAME="Melikgazi"},
                new AGAD.Models.TOWN{Id=509,CITY_ID=38,NAME="Özvatan"},
                new AGAD.Models.TOWN{Id=510,CITY_ID=38,NAME="Pinarbasi"},
                new AGAD.Models.TOWN{Id=511,CITY_ID=38,NAME="Sarioglan"},
                new AGAD.Models.TOWN{Id=512,CITY_ID=38,NAME="Sariz"},
                new AGAD.Models.TOWN{Id=513,CITY_ID=38,NAME="Talas"},
                new AGAD.Models.TOWN{Id=514,CITY_ID=38,NAME="Tomarza"},
                new AGAD.Models.TOWN{Id=515,CITY_ID=38,NAME="Yahyali"},
                new AGAD.Models.TOWN{Id=516,CITY_ID=38,NAME="Yesilhisar"},
                new AGAD.Models.TOWN{Id=517,CITY_ID=39,NAME="Merkez"},
                new AGAD.Models.TOWN{Id=518,CITY_ID=39,NAME="Babaeski"},
                new AGAD.Models.TOWN{Id=519,CITY_ID=39,NAME="Demirköy"},
                new AGAD.Models.TOWN{Id=520,CITY_ID=39,NAME="Kofçaz"},
                new AGAD.Models.TOWN{Id=521,CITY_ID=39,NAME="Lüleburgaz"},
                new AGAD.Models.TOWN{Id=522,CITY_ID=39,NAME="Pehlivanköy"},
                new AGAD.Models.TOWN{Id=523,CITY_ID=39,NAME="Pinarhisar"},
                new AGAD.Models.TOWN{Id=524,CITY_ID=39,NAME="Vize"},
                new AGAD.Models.TOWN{Id=525,CITY_ID=40,NAME="Merkez"},
                new AGAD.Models.TOWN{Id=526,CITY_ID=40,NAME="Akçakent"},
                new AGAD.Models.TOWN{Id=527,CITY_ID=40,NAME="Akpinar"},
                new AGAD.Models.TOWN{Id=528,CITY_ID=40,NAME="Boztepe"},
                new AGAD.Models.TOWN{Id=529,CITY_ID=40,NAME="Çiçekdagi"},
                new AGAD.Models.TOWN{Id=530,CITY_ID=40,NAME="Kaman"},
                new AGAD.Models.TOWN{Id=531,CITY_ID=40,NAME="Mucur"},
                new AGAD.Models.TOWN{Id=532,CITY_ID=41,NAME="Merkez"},
                new AGAD.Models.TOWN{Id=533,CITY_ID=41,NAME="Darica"},
                new AGAD.Models.TOWN{Id=534,CITY_ID=41,NAME="Gebze"},
                new AGAD.Models.TOWN{Id=535,CITY_ID=41,NAME="Gölcük"},
                new AGAD.Models.TOWN{Id=536,CITY_ID=41,NAME="Kandira"},
                new AGAD.Models.TOWN{Id=537,CITY_ID=41,NAME="Karamürsel"},
                new AGAD.Models.TOWN{Id=538,CITY_ID=41,NAME="Körfez"},
                new AGAD.Models.TOWN{Id=539,CITY_ID=42,NAME="Merkez"},
                new AGAD.Models.TOWN{Id=540,CITY_ID=42,NAME="Ahirli"},
                new AGAD.Models.TOWN{Id=541,CITY_ID=42,NAME="Akören"},
                new AGAD.Models.TOWN{Id=542,CITY_ID=42,NAME="Aksehir"},
                new AGAD.Models.TOWN{Id=543,CITY_ID=42,NAME="Altinekin"},
                new AGAD.Models.TOWN{Id=544,CITY_ID=42,NAME="Beysehir"},
                new AGAD.Models.TOWN{Id=545,CITY_ID=42,NAME="Bozkir"},
                new AGAD.Models.TOWN{Id=546,CITY_ID=42,NAME="Derebucak"},
                new AGAD.Models.TOWN{Id=547,CITY_ID=42,NAME="Cihanbeyli"},
                new AGAD.Models.TOWN{Id=548,CITY_ID=42,NAME="Çumra"},
                new AGAD.Models.TOWN{Id=549,CITY_ID=42,NAME="Çeltik"},
                new AGAD.Models.TOWN{Id=550,CITY_ID=42,NAME="Derbent"},
                new AGAD.Models.TOWN{Id=551,CITY_ID=42,NAME="Doganhisar"},
                new AGAD.Models.TOWN{Id=552,CITY_ID=42,NAME="Emirgazi"},
                new AGAD.Models.TOWN{Id=553,CITY_ID=42,NAME="Eregli"},
                new AGAD.Models.TOWN{Id=554,CITY_ID=42,NAME="Güneysinir"},
                new AGAD.Models.TOWN{Id=555,CITY_ID=42,NAME="Halkapinar"},
                new AGAD.Models.TOWN{Id=556,CITY_ID=42,NAME="Hadim"},
                new AGAD.Models.TOWN{Id=557,CITY_ID=42,NAME="Hüyük"},
                new AGAD.Models.TOWN{Id=558,CITY_ID=42,NAME="Ilgin"},
                new AGAD.Models.TOWN{Id=559,CITY_ID=42,NAME="Kadinhani"},
                new AGAD.Models.TOWN{Id=560,CITY_ID=42,NAME="Karapinar"},
                new AGAD.Models.TOWN{Id=561,CITY_ID=42,NAME="Karatay"},
                new AGAD.Models.TOWN{Id=562,CITY_ID=42,NAME="Kulu"},
                new AGAD.Models.TOWN{Id=563,CITY_ID=42,NAME="Meram"},
                new AGAD.Models.TOWN{Id=564,CITY_ID=42,NAME="Sarayönü"},
                new AGAD.Models.TOWN{Id=565,CITY_ID=42,NAME="Selçuklu"},
                new AGAD.Models.TOWN{Id=566,CITY_ID=42,NAME="Seydisehir"},
                new AGAD.Models.TOWN{Id=567,CITY_ID=42,NAME="Taskent"},
                new AGAD.Models.TOWN{Id=568,CITY_ID=42,NAME="Tuzlukçu"},
                new AGAD.Models.TOWN{Id=569,CITY_ID=42,NAME="Yalihöyük"},
                new AGAD.Models.TOWN{Id=570,CITY_ID=42,NAME="Yunak"},
                new AGAD.Models.TOWN{Id=571,CITY_ID=43,NAME="Merkez"},
                new AGAD.Models.TOWN{Id=572,CITY_ID=43,NAME="Altintas"},
                new AGAD.Models.TOWN{Id=573,CITY_ID=43,NAME="Aslanapa"},
                new AGAD.Models.TOWN{Id=574,CITY_ID=43,NAME="Cavdarhisar"},
                new AGAD.Models.TOWN{Id=575,CITY_ID=43,NAME="Domaniç"},
                new AGAD.Models.TOWN{Id=576,CITY_ID=43,NAME="Dumlupinar"},
                new AGAD.Models.TOWN{Id=577,CITY_ID=43,NAME="Emet"},
                new AGAD.Models.TOWN{Id=578,CITY_ID=43,NAME="Gediz"},
                new AGAD.Models.TOWN{Id=579,CITY_ID=43,NAME="Hisarcik"},
                new AGAD.Models.TOWN{Id=580,CITY_ID=43,NAME="Pazarlar"},
                new AGAD.Models.TOWN{Id=581,CITY_ID=43,NAME="Simav"},
                new AGAD.Models.TOWN{Id=582,CITY_ID=43,NAME="Saphane"},
                new AGAD.Models.TOWN{Id=583,CITY_ID=43,NAME="Tavsanli"},
                new AGAD.Models.TOWN{Id=584,CITY_ID=44,NAME="Merkez"},
                new AGAD.Models.TOWN{Id=585,CITY_ID=44,NAME="Akçadag"},
                new AGAD.Models.TOWN{Id=586,CITY_ID=44,NAME="Arapgir"},
                new AGAD.Models.TOWN{Id=587,CITY_ID=44,NAME="Arguvan"},
                new AGAD.Models.TOWN{Id=588,CITY_ID=44,NAME="Battalgazi"},
                new AGAD.Models.TOWN{Id=589,CITY_ID=44,NAME="Darende"},
                new AGAD.Models.TOWN{Id=590,CITY_ID=44,NAME="Dogansehir"},
                new AGAD.Models.TOWN{Id=591,CITY_ID=44,NAME="Doganyol"},
                new AGAD.Models.TOWN{Id=592,CITY_ID=44,NAME="Hekimhan"},
                new AGAD.Models.TOWN{Id=593,CITY_ID=44,NAME="Kale"},
                new AGAD.Models.TOWN{Id=594,CITY_ID=44,NAME="Kuluncak"},
                new AGAD.Models.TOWN{Id=595,CITY_ID=44,NAME="Pötürge"},
                new AGAD.Models.TOWN{Id=596,CITY_ID=44,NAME="Yazihan"},
                new AGAD.Models.TOWN{Id=597,CITY_ID=44,NAME="Yesilyurt"},
                new AGAD.Models.TOWN{Id=598,CITY_ID=45,NAME="Merkez"},
                new AGAD.Models.TOWN{Id=599,CITY_ID=45,NAME="Ahmetli"},
                new AGAD.Models.TOWN{Id=600,CITY_ID=45,NAME="Akhisar"},
                new AGAD.Models.TOWN{Id=601,CITY_ID=45,NAME="Alasehir"},
                new AGAD.Models.TOWN{Id=602,CITY_ID=45,NAME="Demirci"},
                new AGAD.Models.TOWN{Id=603,CITY_ID=45,NAME="Gölmarmara"},
                new AGAD.Models.TOWN{Id=604,CITY_ID=45,NAME="Gördes"},
                new AGAD.Models.TOWN{Id=605,CITY_ID=45,NAME="Kirkagaç"},
                new AGAD.Models.TOWN{Id=606,CITY_ID=45,NAME="Köprübasi"},
                new AGAD.Models.TOWN{Id=607,CITY_ID=45,NAME="Kula"},
                new AGAD.Models.TOWN{Id=608,CITY_ID=45,NAME="Salihli"},
                new AGAD.Models.TOWN{Id=609,CITY_ID=45,NAME="Sarigöl"},
                new AGAD.Models.TOWN{Id=610,CITY_ID=45,NAME="Saruhanli"},
                new AGAD.Models.TOWN{Id=611,CITY_ID=45,NAME="Selendi"},
                new AGAD.Models.TOWN{Id=612,CITY_ID=45,NAME="Soma"},
                new AGAD.Models.TOWN{Id=613,CITY_ID=45,NAME="Turgutlu"},
                new AGAD.Models.TOWN{Id=614,CITY_ID=46,NAME="Merkez"},
                new AGAD.Models.TOWN{Id=615,CITY_ID=46,NAME="Afsin"},
                new AGAD.Models.TOWN{Id=616,CITY_ID=46,NAME="Andirin"},
                new AGAD.Models.TOWN{Id=617,CITY_ID=46,NAME="Çaglayancer"},
                new AGAD.Models.TOWN{Id=618,CITY_ID=46,NAME="Ekinözü"},
                new AGAD.Models.TOWN{Id=619,CITY_ID=46,NAME="Elbistan"},
                new AGAD.Models.TOWN{Id=620,CITY_ID=46,NAME="Göksun"},
                new AGAD.Models.TOWN{Id=621,CITY_ID=46,NAME="Nurhak"},
                new AGAD.Models.TOWN{Id=622,CITY_ID=46,NAME="Pazarcik"},
                new AGAD.Models.TOWN{Id=623,CITY_ID=46,NAME="Türkoglu"},
                new AGAD.Models.TOWN{Id=624,CITY_ID=47,NAME="Merkez"},
                new AGAD.Models.TOWN{Id=625,CITY_ID=47,NAME="Dargeçit"},
                new AGAD.Models.TOWN{Id=626,CITY_ID=47,NAME="Derik"},
                new AGAD.Models.TOWN{Id=627,CITY_ID=47,NAME="Kiziltepe"},
                new AGAD.Models.TOWN{Id=628,CITY_ID=47,NAME="MazIdagi"},
                new AGAD.Models.TOWN{Id=629,CITY_ID=47,NAME="MIdyat"},
                new AGAD.Models.TOWN{Id=630,CITY_ID=47,NAME="Nusaybin"},
                new AGAD.Models.TOWN{Id=631,CITY_ID=47,NAME="Ömerli"},
                new AGAD.Models.TOWN{Id=632,CITY_ID=47,NAME="Savur"},
                new AGAD.Models.TOWN{Id=633,CITY_ID=47,NAME="Yesilli"},
                new AGAD.Models.TOWN{Id=634,CITY_ID=48,NAME="Merkez"},
                new AGAD.Models.TOWN{Id=635,CITY_ID=48,NAME="Bodrum"},
                new AGAD.Models.TOWN{Id=636,CITY_ID=48,NAME="Dalaman"},
                new AGAD.Models.TOWN{Id=637,CITY_ID=48,NAME="Datça"},
                new AGAD.Models.TOWN{Id=638,CITY_ID=48,NAME="Fethiye"},
                new AGAD.Models.TOWN{Id=639,CITY_ID=48,NAME="KavaklIdere"},
                new AGAD.Models.TOWN{Id=640,CITY_ID=48,NAME="Köycegiz"},
                new AGAD.Models.TOWN{Id=641,CITY_ID=48,NAME="Marmaris"},
                new AGAD.Models.TOWN{Id=642,CITY_ID=48,NAME="Milas"},
                new AGAD.Models.TOWN{Id=643,CITY_ID=48,NAME="Ortaca"},
                new AGAD.Models.TOWN{Id=644,CITY_ID=48,NAME="Ula"},
                new AGAD.Models.TOWN{Id=645,CITY_ID=48,NAME="Yatagan"},
                new AGAD.Models.TOWN{Id=646,CITY_ID=49,NAME="Merkez"},
                new AGAD.Models.TOWN{Id=647,CITY_ID=49,NAME="Bulanik"},
                new AGAD.Models.TOWN{Id=648,CITY_ID=49,NAME="Hasköy"},
                new AGAD.Models.TOWN{Id=649,CITY_ID=49,NAME="Korkut"},
                new AGAD.Models.TOWN{Id=650,CITY_ID=49,NAME="Malazgirt"},
                new AGAD.Models.TOWN{Id=651,CITY_ID=49,NAME="Varto"},
                new AGAD.Models.TOWN{Id=652,CITY_ID=50,NAME="Merkez"},
                new AGAD.Models.TOWN{Id=653,CITY_ID=50,NAME="Acigöl"},
                new AGAD.Models.TOWN{Id=654,CITY_ID=50,NAME="Avanos"},
                new AGAD.Models.TOWN{Id=655,CITY_ID=50,NAME="Derinkuyu"},
                new AGAD.Models.TOWN{Id=656,CITY_ID=50,NAME="Gülsehir"},
                new AGAD.Models.TOWN{Id=657,CITY_ID=50,NAME="Hacibektas"},
                new AGAD.Models.TOWN{Id=658,CITY_ID=50,NAME="Kozakli"},
                new AGAD.Models.TOWN{Id=659,CITY_ID=50,NAME="Ürgüp"},
                new AGAD.Models.TOWN{Id=660,CITY_ID=51,NAME="Merkez"},
                new AGAD.Models.TOWN{Id=661,CITY_ID=51,NAME="Altunhisar"},
                new AGAD.Models.TOWN{Id=662,CITY_ID=51,NAME="Bor"},
                new AGAD.Models.TOWN{Id=663,CITY_ID=51,NAME="Çamardi"},
                new AGAD.Models.TOWN{Id=664,CITY_ID=51,NAME="Çiftlik"},
                new AGAD.Models.TOWN{Id=665,CITY_ID=51,NAME="Ulukisla"},
                new AGAD.Models.TOWN{Id=666,CITY_ID=52,NAME="Merkez"},
                new AGAD.Models.TOWN{Id=667,CITY_ID=52,NAME="Akkus"},
                new AGAD.Models.TOWN{Id=668,CITY_ID=52,NAME="Aybasti"},
                new AGAD.Models.TOWN{Id=669,CITY_ID=52,NAME="Çamas"},
                new AGAD.Models.TOWN{Id=670,CITY_ID=52,NAME="Çatalpinar"},
                new AGAD.Models.TOWN{Id=671,CITY_ID=52,NAME="Çaybasi"},
                new AGAD.Models.TOWN{Id=672,CITY_ID=52,NAME="Fatsa"},
                new AGAD.Models.TOWN{Id=673,CITY_ID=52,NAME="Gölköy"},
                new AGAD.Models.TOWN{Id=674,CITY_ID=52,NAME="Gölyali"},
                new AGAD.Models.TOWN{Id=675,CITY_ID=52,NAME="Gürgentepe"},
                new AGAD.Models.TOWN{Id=676,CITY_ID=52,NAME="Ikizce"},
                new AGAD.Models.TOWN{Id=677,CITY_ID=52,NAME="Korgan"},
                new AGAD.Models.TOWN{Id=678,CITY_ID=52,NAME="Kabadüz"},
                new AGAD.Models.TOWN{Id=679,CITY_ID=52,NAME="Kabatas"},
                new AGAD.Models.TOWN{Id=680,CITY_ID=52,NAME="Kumru"},
                new AGAD.Models.TOWN{Id=681,CITY_ID=52,NAME="Mesudiye"},
                new AGAD.Models.TOWN{Id=682,CITY_ID=52,NAME="Persembe"},
                new AGAD.Models.TOWN{Id=683,CITY_ID=52,NAME="Ulubey"},
                new AGAD.Models.TOWN{Id=684,CITY_ID=52,NAME="Ünye"},
                new AGAD.Models.TOWN{Id=685,CITY_ID=53,NAME="Merkez"},
                new AGAD.Models.TOWN{Id=686,CITY_ID=53,NAME="Ardesen"},
                new AGAD.Models.TOWN{Id=687,CITY_ID=53,NAME="Çamlihemsin"},
                new AGAD.Models.TOWN{Id=688,CITY_ID=53,NAME="Çayeli"},
                new AGAD.Models.TOWN{Id=689,CITY_ID=53,NAME="Derepazari"},
                new AGAD.Models.TOWN{Id=690,CITY_ID=53,NAME="Findikli"},
                new AGAD.Models.TOWN{Id=691,CITY_ID=53,NAME="Güneysu"},
                new AGAD.Models.TOWN{Id=692,CITY_ID=53,NAME="Hemsin"},
                new AGAD.Models.TOWN{Id=693,CITY_ID=53,NAME="Ikizdere"},
                new AGAD.Models.TOWN{Id=694,CITY_ID=53,NAME="IyIdere"},
                new AGAD.Models.TOWN{Id=695,CITY_ID=53,NAME="Kalkandere"},
                new AGAD.Models.TOWN{Id=696,CITY_ID=53,NAME="Pazar"},
                new AGAD.Models.TOWN{Id=697,CITY_ID=54,NAME="Merkez"},
                new AGAD.Models.TOWN{Id=698,CITY_ID=54,NAME="Akyazi"},
                new AGAD.Models.TOWN{Id=699,CITY_ID=54,NAME="Ferizli"},
                new AGAD.Models.TOWN{Id=700,CITY_ID=54,NAME="Geyve"},
                new AGAD.Models.TOWN{Id=701,CITY_ID=54,NAME="Hendek"},
                new AGAD.Models.TOWN{Id=702,CITY_ID=54,NAME="Karapürçek"},
                new AGAD.Models.TOWN{Id=703,CITY_ID=54,NAME="Karasu"},
                new AGAD.Models.TOWN{Id=704,CITY_ID=54,NAME="Kaynarca"},
                new AGAD.Models.TOWN{Id=705,CITY_ID=54,NAME="Kocaali"},
                new AGAD.Models.TOWN{Id=706,CITY_ID=54,NAME="Pamukova"},
                new AGAD.Models.TOWN{Id=707,CITY_ID=54,NAME="Sapanca"},
                new AGAD.Models.TOWN{Id=708,CITY_ID=54,NAME="Sögütlü"},
                new AGAD.Models.TOWN{Id=709,CITY_ID=54,NAME="Tarakli"},
                new AGAD.Models.TOWN{Id=710,CITY_ID=55,NAME="Merkez"},
                new AGAD.Models.TOWN{Id=711,CITY_ID=55,NAME="Alaçam"},
                new AGAD.Models.TOWN{Id=712,CITY_ID=55,NAME="Asarcik"},
                new AGAD.Models.TOWN{Id=713,CITY_ID=55,NAME="Ayvacik"},
                new AGAD.Models.TOWN{Id=714,CITY_ID=55,NAME="Bafra"},
                new AGAD.Models.TOWN{Id=715,CITY_ID=55,NAME="Çarsamba"},
                new AGAD.Models.TOWN{Id=716,CITY_ID=55,NAME="Havza"},
                new AGAD.Models.TOWN{Id=717,CITY_ID=55,NAME="Kavak"},
                new AGAD.Models.TOWN{Id=718,CITY_ID=55,NAME="Ladik"},
                new AGAD.Models.TOWN{Id=719,CITY_ID=55,NAME="19mayis"},
                new AGAD.Models.TOWN{Id=720,CITY_ID=55,NAME="Salipazari"},
                new AGAD.Models.TOWN{Id=721,CITY_ID=55,NAME="Tekkeköy"},
                new AGAD.Models.TOWN{Id=722,CITY_ID=55,NAME="Terme"},
                new AGAD.Models.TOWN{Id=723,CITY_ID=55,NAME="Vezirköprü"},
                new AGAD.Models.TOWN{Id=724,CITY_ID=55,NAME="Yakakent"},
                new AGAD.Models.TOWN{Id=725,CITY_ID=56,NAME="Merkez"},
                new AGAD.Models.TOWN{Id=726,CITY_ID=56,NAME="Aydinlar"},
                new AGAD.Models.TOWN{Id=727,CITY_ID=56,NAME="Baykan"},
                new AGAD.Models.TOWN{Id=728,CITY_ID=56,NAME="Eruh"},
                new AGAD.Models.TOWN{Id=729,CITY_ID=56,NAME="Kozluk"},
                new AGAD.Models.TOWN{Id=730,CITY_ID=56,NAME="Kurtalan"},
                new AGAD.Models.TOWN{Id=731,CITY_ID=56,NAME="Pervari"},
                new AGAD.Models.TOWN{Id=732,CITY_ID=56,NAME="Sirvan"},
                new AGAD.Models.TOWN{Id=733,CITY_ID=57,NAME="Merkez"},
                new AGAD.Models.TOWN{Id=734,CITY_ID=57,NAME="Ayancik"},
                new AGAD.Models.TOWN{Id=735,CITY_ID=57,NAME="Boyabat"},
                new AGAD.Models.TOWN{Id=736,CITY_ID=57,NAME="Dikmen"},
                new AGAD.Models.TOWN{Id=737,CITY_ID=57,NAME="Duragan"},
                new AGAD.Models.TOWN{Id=738,CITY_ID=57,NAME="Erfelek"},
                new AGAD.Models.TOWN{Id=739,CITY_ID=57,NAME="Gerze"},
                new AGAD.Models.TOWN{Id=740,CITY_ID=57,NAME="Saraydüzü"},
                new AGAD.Models.TOWN{Id=741,CITY_ID=57,NAME="Türkeli"},
                new AGAD.Models.TOWN{Id=742,CITY_ID=58,NAME="Merkez"},
                new AGAD.Models.TOWN{Id=743,CITY_ID=58,NAME="Akincilar"},
                new AGAD.Models.TOWN{Id=744,CITY_ID=58,NAME="Altinyayla"},
                new AGAD.Models.TOWN{Id=745,CITY_ID=58,NAME="Divrigi"},
                new AGAD.Models.TOWN{Id=746,CITY_ID=58,NAME="Dogansar"},
                new AGAD.Models.TOWN{Id=747,CITY_ID=58,NAME="Gemerek"},
                new AGAD.Models.TOWN{Id=748,CITY_ID=58,NAME="Gölova"},
                new AGAD.Models.TOWN{Id=749,CITY_ID=58,NAME="Gürün"},
                new AGAD.Models.TOWN{Id=750,CITY_ID=58,NAME="Hafik"},
                new AGAD.Models.TOWN{Id=751,CITY_ID=58,NAME="Imranli"},
                new AGAD.Models.TOWN{Id=752,CITY_ID=58,NAME="Kangal"},
                new AGAD.Models.TOWN{Id=753,CITY_ID=58,NAME="Koyulhisar"},
                new AGAD.Models.TOWN{Id=754,CITY_ID=58,NAME="Susehri"},
                new AGAD.Models.TOWN{Id=755,CITY_ID=58,NAME="Sarkisla"},
                new AGAD.Models.TOWN{Id=756,CITY_ID=58,NAME="Ulas"},
                new AGAD.Models.TOWN{Id=757,CITY_ID=58,NAME="Yildizeli"},
                new AGAD.Models.TOWN{Id=758,CITY_ID=58,NAME="Zara"},
                new AGAD.Models.TOWN{Id=759,CITY_ID=59,NAME="Merkez"},
                new AGAD.Models.TOWN{Id=760,CITY_ID=59,NAME="Çerkezköy"},
                new AGAD.Models.TOWN{Id=761,CITY_ID=59,NAME="Çorlu"},
                new AGAD.Models.TOWN{Id=762,CITY_ID=59,NAME="Hayrabolu"},
                new AGAD.Models.TOWN{Id=763,CITY_ID=59,NAME="Malkara"},
                new AGAD.Models.TOWN{Id=764,CITY_ID=59,NAME="Marmaraeregli"},
                new AGAD.Models.TOWN{Id=765,CITY_ID=59,NAME="Muratli"},
                new AGAD.Models.TOWN{Id=766,CITY_ID=59,NAME="Saray"},
                new AGAD.Models.TOWN{Id=767,CITY_ID=59,NAME="Sarköy"},
                new AGAD.Models.TOWN{Id=768,CITY_ID=60,NAME="Merkez"},
                new AGAD.Models.TOWN{Id=769,CITY_ID=60,NAME="Almus"},
                new AGAD.Models.TOWN{Id=770,CITY_ID=60,NAME="Artova"},
                new AGAD.Models.TOWN{Id=771,CITY_ID=60,NAME="Basçiftlik"},
                new AGAD.Models.TOWN{Id=772,CITY_ID=60,NAME="Erbaa"},
                new AGAD.Models.TOWN{Id=773,CITY_ID=60,NAME="Niksar"},
                new AGAD.Models.TOWN{Id=774,CITY_ID=60,NAME="Pazar"},
                new AGAD.Models.TOWN{Id=775,CITY_ID=60,NAME="Resadiye"},
                new AGAD.Models.TOWN{Id=776,CITY_ID=60,NAME="Sulusaray"},
                new AGAD.Models.TOWN{Id=777,CITY_ID=60,NAME="Turhal"},
                new AGAD.Models.TOWN{Id=778,CITY_ID=60,NAME="Yesilyurt"},
                new AGAD.Models.TOWN{Id=779,CITY_ID=60,NAME="Zile"},
                new AGAD.Models.TOWN{Id=780,CITY_ID=61,NAME="Merkez"},
                new AGAD.Models.TOWN{Id=781,CITY_ID=61,NAME="Akçaabat"},
                new AGAD.Models.TOWN{Id=782,CITY_ID=61,NAME="Arakli"},
                new AGAD.Models.TOWN{Id=783,CITY_ID=61,NAME="Arsin"},
                new AGAD.Models.TOWN{Id=784,CITY_ID=61,NAME="Besikdüzü"},
                new AGAD.Models.TOWN{Id=785,CITY_ID=61,NAME="Çarsibasi"},
                new AGAD.Models.TOWN{Id=786,CITY_ID=61,NAME="Çaykara"},
                new AGAD.Models.TOWN{Id=787,CITY_ID=61,NAME="Dernekpazar"},
                new AGAD.Models.TOWN{Id=788,CITY_ID=61,NAME="Düzköy"},
                new AGAD.Models.TOWN{Id=789,CITY_ID=61,NAME="Hayrat"},
                new AGAD.Models.TOWN{Id=790,CITY_ID=61,NAME="Köprübasi"},
                new AGAD.Models.TOWN{Id=791,CITY_ID=61,NAME="Maçka"},
                new AGAD.Models.TOWN{Id=792,CITY_ID=61,NAME="Of"},
                new AGAD.Models.TOWN{Id=793,CITY_ID=61,NAME="Sürmene"},
                new AGAD.Models.TOWN{Id=794,CITY_ID=61,NAME="Salpazari"},
                new AGAD.Models.TOWN{Id=795,CITY_ID=61,NAME="Tonya"},
                new AGAD.Models.TOWN{Id=796,CITY_ID=61,NAME="Vakfikebir"},
                new AGAD.Models.TOWN{Id=797,CITY_ID=61,NAME="Yomra"},
                new AGAD.Models.TOWN{Id=798,CITY_ID=62,NAME="Merkez"},
                new AGAD.Models.TOWN{Id=799,CITY_ID=62,NAME="Çemisgezek"},
                new AGAD.Models.TOWN{Id=800,CITY_ID=62,NAME="Hozat"},
                new AGAD.Models.TOWN{Id=801,CITY_ID=62,NAME="Mazgirt"},
                new AGAD.Models.TOWN{Id=802,CITY_ID=62,NAME="Nazimiye"},
                new AGAD.Models.TOWN{Id=803,CITY_ID=62,NAME="Ovacik"},
                new AGAD.Models.TOWN{Id=804,CITY_ID=62,NAME="Pertek"},
                new AGAD.Models.TOWN{Id=805,CITY_ID=62,NAME="Pülümür"},
                new AGAD.Models.TOWN{Id=806,CITY_ID=63,NAME="Merkez"},
                new AGAD.Models.TOWN{Id=807,CITY_ID=63,NAME="Akçakale"},
                new AGAD.Models.TOWN{Id=808,CITY_ID=63,NAME="Birecik"},
                new AGAD.Models.TOWN{Id=809,CITY_ID=63,NAME="Bozova"},
                new AGAD.Models.TOWN{Id=810,CITY_ID=63,NAME="Ceylanpinar"},
                new AGAD.Models.TOWN{Id=811,CITY_ID=63,NAME="Halfeti"},
                new AGAD.Models.TOWN{Id=812,CITY_ID=63,NAME="Harran"},
                new AGAD.Models.TOWN{Id=813,CITY_ID=63,NAME="Hilvan"},
                new AGAD.Models.TOWN{Id=814,CITY_ID=63,NAME="Siverek"},
                new AGAD.Models.TOWN{Id=815,CITY_ID=63,NAME="Suruç"},
                new AGAD.Models.TOWN{Id=816,CITY_ID=63,NAME="Viransehir"},
                new AGAD.Models.TOWN{Id=817,CITY_ID=64,NAME="Merkez"},
                new AGAD.Models.TOWN{Id=818,CITY_ID=64,NAME="Banaz"},
                new AGAD.Models.TOWN{Id=819,CITY_ID=64,NAME="Esme"},
                new AGAD.Models.TOWN{Id=820,CITY_ID=64,NAME="Karahalli"},
                new AGAD.Models.TOWN{Id=821,CITY_ID=64,NAME="Sivasli"},
                new AGAD.Models.TOWN{Id=822,CITY_ID=64,NAME="Ulubey"},
                new AGAD.Models.TOWN{Id=823,CITY_ID=65,NAME="Merkez"},
                new AGAD.Models.TOWN{Id=824,CITY_ID=65,NAME="Bahçesaray"},
                new AGAD.Models.TOWN{Id=825,CITY_ID=65,NAME="Baskale"},
                new AGAD.Models.TOWN{Id=826,CITY_ID=65,NAME="Çaldiran"},
                new AGAD.Models.TOWN{Id=827,CITY_ID=65,NAME="Çatak"},
                new AGAD.Models.TOWN{Id=828,CITY_ID=65,NAME="Edremit"},
                new AGAD.Models.TOWN{Id=829,CITY_ID=65,NAME="Ercis"},
                new AGAD.Models.TOWN{Id=830,CITY_ID=65,NAME="Gevas"},
                new AGAD.Models.TOWN{Id=831,CITY_ID=65,NAME="Gürpinar"},
                new AGAD.Models.TOWN{Id=832,CITY_ID=65,NAME="Muradiye"},
                new AGAD.Models.TOWN{Id=833,CITY_ID=65,NAME="Özalp"},
                new AGAD.Models.TOWN{Id=834,CITY_ID=65,NAME="Saray"},
                new AGAD.Models.TOWN{Id=835,CITY_ID=66,NAME="Merkez"},
                new AGAD.Models.TOWN{Id=836,CITY_ID=66,NAME="Akdagmadeni"},
                new AGAD.Models.TOWN{Id=837,CITY_ID=66,NAME="Aydincik"},
                new AGAD.Models.TOWN{Id=838,CITY_ID=66,NAME="Bogazliyan"},
                new AGAD.Models.TOWN{Id=839,CITY_ID=66,NAME="Çandir"},
                new AGAD.Models.TOWN{Id=840,CITY_ID=66,NAME="Çayiralan"},
                new AGAD.Models.TOWN{Id=841,CITY_ID=66,NAME="Çekerek"},
                new AGAD.Models.TOWN{Id=842,CITY_ID=66,NAME="Kadisehri"},
                new AGAD.Models.TOWN{Id=843,CITY_ID=66,NAME="Sarikaya"},
                new AGAD.Models.TOWN{Id=844,CITY_ID=66,NAME="Saraykent"},
                new AGAD.Models.TOWN{Id=845,CITY_ID=66,NAME="Sorgun"},
                new AGAD.Models.TOWN{Id=846,CITY_ID=66,NAME="Sefaatli"},
                new AGAD.Models.TOWN{Id=847,CITY_ID=66,NAME="Yenifakili"},
                new AGAD.Models.TOWN{Id=848,CITY_ID=66,NAME="Yerköy"},
                new AGAD.Models.TOWN{Id=849,CITY_ID=67,NAME="Merkez"},
                new AGAD.Models.TOWN{Id=850,CITY_ID=67,NAME="Alapli"},
                new AGAD.Models.TOWN{Id=851,CITY_ID=67,NAME="Çamoluk"},
                new AGAD.Models.TOWN{Id=852,CITY_ID=67,NAME="Çaycuma"},
                new AGAD.Models.TOWN{Id=853,CITY_ID=67,NAME="Devrek"},
                new AGAD.Models.TOWN{Id=854,CITY_ID=67,NAME="Eflani"},
                new AGAD.Models.TOWN{Id=855,CITY_ID=67,NAME="Eregli"},
                new AGAD.Models.TOWN{Id=856,CITY_ID=67,NAME="Gökçebey"},
                new AGAD.Models.TOWN{Id=857,CITY_ID=68,NAME="Merkez"},
                new AGAD.Models.TOWN{Id=858,CITY_ID=68,NAME="Agaçören"},
                new AGAD.Models.TOWN{Id=859,CITY_ID=68,NAME="Eskil"},
                new AGAD.Models.TOWN{Id=860,CITY_ID=68,NAME="Gülagaç"},
                new AGAD.Models.TOWN{Id=861,CITY_ID=68,NAME="Güzelyurt"},
                new AGAD.Models.TOWN{Id=862,CITY_ID=68,NAME="Ortaköy"},
                new AGAD.Models.TOWN{Id=863,CITY_ID=68,NAME="Sariyahsi"},
                new AGAD.Models.TOWN{Id=864,CITY_ID=69,NAME="Merkez"},
                new AGAD.Models.TOWN{Id=865,CITY_ID=69,NAME="Aydintepe"},
                new AGAD.Models.TOWN{Id=866,CITY_ID=69,NAME="Demirözü"},
                new AGAD.Models.TOWN{Id=867,CITY_ID=70,NAME="Merkez"},
                new AGAD.Models.TOWN{Id=868,CITY_ID=70,NAME="Ayranci"},
                new AGAD.Models.TOWN{Id=869,CITY_ID=70,NAME="Basyayla"},
                new AGAD.Models.TOWN{Id=870,CITY_ID=70,NAME="Ermenek"},
                new AGAD.Models.TOWN{Id=871,CITY_ID=70,NAME="Kazimkarabekir"},
                new AGAD.Models.TOWN{Id=872,CITY_ID=70,NAME="Sariveliler"},
                new AGAD.Models.TOWN{Id=873,CITY_ID=71,NAME="Merkez"},
                new AGAD.Models.TOWN{Id=874,CITY_ID=71,NAME="Bahsili"},
                new AGAD.Models.TOWN{Id=875,CITY_ID=71,NAME="Bagliseyh"},
                new AGAD.Models.TOWN{Id=876,CITY_ID=71,NAME="Çelebi"},
                new AGAD.Models.TOWN{Id=877,CITY_ID=71,NAME="Delice"},
                new AGAD.Models.TOWN{Id=878,CITY_ID=71,NAME="Karakeçili"},
                new AGAD.Models.TOWN{Id=879,CITY_ID=71,NAME="Keskin"},
                new AGAD.Models.TOWN{Id=880,CITY_ID=71,NAME="Sulakyurt"},
                new AGAD.Models.TOWN{Id=881,CITY_ID=71,NAME="Yahsihan"},
                new AGAD.Models.TOWN{Id=882,CITY_ID=72,NAME="Merkez"},
                new AGAD.Models.TOWN{Id=883,CITY_ID=72,NAME="Gercüs"},
                new AGAD.Models.TOWN{Id=884,CITY_ID=72,NAME="Hasankeyf"},
                new AGAD.Models.TOWN{Id=885,CITY_ID=72,NAME="Besiri"},
                new AGAD.Models.TOWN{Id=886,CITY_ID=72,NAME="Kozluk"},
                new AGAD.Models.TOWN{Id=887,CITY_ID=72,NAME="Sason"},
                new AGAD.Models.TOWN{Id=888,CITY_ID=73,NAME="Merkez"},
                new AGAD.Models.TOWN{Id=889,CITY_ID=73,NAME="Beytüsseba"},
                new AGAD.Models.TOWN{Id=890,CITY_ID=73,NAME="Uludere"},
                new AGAD.Models.TOWN{Id=891,CITY_ID=73,NAME="Cizre"},
                new AGAD.Models.TOWN{Id=892,CITY_ID=73,NAME="Idil"},
                new AGAD.Models.TOWN{Id=893,CITY_ID=73,NAME="Silopi"},
                new AGAD.Models.TOWN{Id=894,CITY_ID=73,NAME="Güçlükonak"},
                new AGAD.Models.TOWN{Id=895,CITY_ID=74,NAME="Merkez"},
                new AGAD.Models.TOWN{Id=896,CITY_ID=74,NAME="Amasra"},
                new AGAD.Models.TOWN{Id=897,CITY_ID=74,NAME="Kurucasile"},
                new AGAD.Models.TOWN{Id=898,CITY_ID=74,NAME="Ulus"},
                new AGAD.Models.TOWN{Id=899,CITY_ID=75,NAME="Merkez"},
                new AGAD.Models.TOWN{Id=900,CITY_ID=75,NAME="Çildir"},
                new AGAD.Models.TOWN{Id=901,CITY_ID=75,NAME="Damal"},
                new AGAD.Models.TOWN{Id=902,CITY_ID=75,NAME="Göle"},
                new AGAD.Models.TOWN{Id=903,CITY_ID=75,NAME="Hanak"},
                new AGAD.Models.TOWN{Id=904,CITY_ID=75,NAME="Posof"},
                new AGAD.Models.TOWN{Id=905,CITY_ID=76,NAME="Merkez"},
                new AGAD.Models.TOWN{Id=906,CITY_ID=76,NAME="Aralik"},
                new AGAD.Models.TOWN{Id=907,CITY_ID=76,NAME="Karakoyunlu"},
                new AGAD.Models.TOWN{Id=908,CITY_ID=76,NAME="Tuzluca"},
                new AGAD.Models.TOWN{Id=909,CITY_ID=77,NAME="Merkez"},
                new AGAD.Models.TOWN{Id=910,CITY_ID=77,NAME="Altinova"},
                new AGAD.Models.TOWN{Id=911,CITY_ID=77,NAME="Armutlu"},
                new AGAD.Models.TOWN{Id=912,CITY_ID=77,NAME="Cinarcik"},
                new AGAD.Models.TOWN{Id=913,CITY_ID=77,NAME="Ciftlikkoy"},
                new AGAD.Models.TOWN{Id=914,CITY_ID=77,NAME="Termal"},
                new AGAD.Models.TOWN{Id=915,CITY_ID=78,NAME="Merkez"},
                new AGAD.Models.TOWN{Id=916,CITY_ID=78,NAME="Eflani"},
                new AGAD.Models.TOWN{Id=917,CITY_ID=78,NAME="Eskipazar"},
                new AGAD.Models.TOWN{Id=918,CITY_ID=78,NAME="Ovacik"},
                new AGAD.Models.TOWN{Id=919,CITY_ID=78,NAME="Safranbolu"},
                new AGAD.Models.TOWN{Id=920,CITY_ID=78,NAME="Yenice"},
                new AGAD.Models.TOWN{Id=921,CITY_ID=79,NAME="Merkez"},
                new AGAD.Models.TOWN{Id=922,CITY_ID=79,NAME="Elbeyli"},
                new AGAD.Models.TOWN{Id=923,CITY_ID=79,NAME="Musabeyli"},
                new AGAD.Models.TOWN{Id=924,CITY_ID=79,NAME="Polateli"},
                new AGAD.Models.TOWN{Id=925,CITY_ID=80,NAME="Merkez"},
                new AGAD.Models.TOWN{Id=926,CITY_ID=80,NAME="Bahçe"},
                new AGAD.Models.TOWN{Id=927,CITY_ID=80,NAME="Hasanbeyli"},
                new AGAD.Models.TOWN{Id=928,CITY_ID=80,NAME="Düziçi"},
                new AGAD.Models.TOWN{Id=929,CITY_ID=80,NAME="Kadirli"},
                new AGAD.Models.TOWN{Id=930,CITY_ID=80,NAME="Sunbas"},
                new AGAD.Models.TOWN{Id=931,CITY_ID=80,NAME="Toprakkale"},
                new AGAD.Models.TOWN{Id=932,CITY_ID=81,NAME="Merkez"},
                new AGAD.Models.TOWN{Id=933,CITY_ID=81,NAME="Akçakoca"},
                new AGAD.Models.TOWN{Id=934,CITY_ID=81,NAME="Cumayeri"},
                new AGAD.Models.TOWN{Id=935,CITY_ID=81,NAME="Çilimli"},
                new AGAD.Models.TOWN{Id=936,CITY_ID=81,NAME="Gölyaka"},
                new AGAD.Models.TOWN{Id=937,CITY_ID=81,NAME="Gümüsova"},
                new AGAD.Models.TOWN{Id=938,CITY_ID=81,NAME="Kaynasli"},
                new AGAD.Models.TOWN{Id=939,CITY_ID=81,NAME="Yigilca"}
            };
            temp.ForEach(f => context.TOWNs.AddOrUpdate(p => p.Id, f));
            context.SaveChanges();
        }
        private void seedAGADCONFIRMSTATE(AGAD.Models.agadContext context)
        {
            var tempItems = new List<Models.CONFIRMSTATE>{
                new Models.CONFIRMSTATE{
                   Id=(int)Models.CONFIRMSTATEENUM.NOTACCEPTED,
                   NAME="NOT ACCEPTED",
                   NAMEUNICODE="notaccepted",
                   AGADs=null
                },
                new Models.CONFIRMSTATE{
                   Id=(int)Models.CONFIRMSTATEENUM.ACCEPTED,
                   NAME="ACCEPTED",
                   NAMEUNICODE="accepted",
                   AGADs=null
                },
                new Models.CONFIRMSTATE{
                   Id=(int)Models.CONFIRMSTATEENUM.CANCELLED,
                   NAME="CANCELLED",
                   NAMEUNICODE="cancelled",
                   AGADs=null
                },
                new Models.CONFIRMSTATE{
                   Id=(int)Models.CONFIRMSTATEENUM.PROCESSING,
                   NAME="PROCESSING",
                   NAMEUNICODE="processing",
                   AGADs=null
                },
            };
            tempItems.ForEach(f => context.CONFIRMSTATEs.AddOrUpdate(p => p.Id, f));
            context.SaveChanges();
        }

        protected override void Seed(Models.agadContext context)
        {
            //seedAGADTYPE(context);
            //seedAGADCONFIRMSTATE(context);
            //seedAGADTOWN(context);
            //seedAGADCITY(context);
            //seedUSER(context);
            //seedAGAD(context);
            //seedIMAGEPATHS(context);
            base.Seed(context);
        }

        private void seedIMAGEPATHS(Models.agadContext context)
        {
            var tempItems = new List<Models.IMAGEPATH>{
                new Models.IMAGEPATH{
                  PATH="~/Content/Images/afadlogo.png",
                  AGAD_ID=2
                   
                }
            };
            tempItems.ForEach(f => context.IMAGEPATHs.AddOrUpdate(p => p.Id, f));
            context.SaveChanges();
        }

        private void seedUSER(Models.agadContext context)
        {
            var tempItems = new List<Models.USER>{
                new Models.USER{
                   TC="12345678911",
                   SURNAME="default",
                   NAME="default",
                   ADRES="adres",
                   EMAIL="admin@admin.com",
                   PASS="123456",
                   PHONE="1245678",
                   
                }
            };
            tempItems.ForEach(f => context.USERs.AddOrUpdate(p => p.TC, f));
            context.SaveChanges();
        }

        private void seedAGAD(Models.agadContext context)
        {
            var tempItems = new List<Models.AGAD>{
                new Models.AGAD{
                   AGADTYPE=1,
                   CITY=1,
                   COMMENT="deneme",
                   CONFIRMCOMMENT="hjgjhgjh",
                   CONFIRMSTATEID=1,
                   DISTINCT_REGION="hkjhkhkh",
                   EFFECTTEDAREA="jkhkhkh",
                   ENDDATE=DateTime.Now,
                   STARTDATE=DateTime.Now,
                   USER_TC="12345678911"
                   
                }
            };
            tempItems.ForEach(f => context.AGADs.AddOrUpdate(p => p.Id, f));
            context.SaveChanges();
        }
    }
}
